### ISSUE TITLE
Drawer menu on rtl languages,

### ISSUE THREAD

**Issue by diablo6006** [StarCitizenTools/mediawiki-skins-Citizen#170]
## Describe the Bug
i noticed that drawer menu on rtl languages has an issue with the X buttun that closes the drawer. 

how i solve it:
1. Go to 'mediawiki:common.css'
2. Add the following:

#mw-drawer-button:checked ~ #mw-drawer-button-icon #mw-drawer-button-icon-2 {
    transform: rotate(45deg) translate(-5px,-7px);
}
#mw-drawer-button:checked ~ #mw-drawer-button-icon #mw-drawer-button-icon-3 {
    transform: rotate(-45deg) translate(2px,-2px);
}

![drawer1](https://user-images.githubusercontent.com/17708182/89932467-b7436b80-dc1e-11ea-8701-7ca3119f1060.png)

**Comment by alistair3149** [comment]
Thanks for the report! I'll look into fixing it in the next patch.

**Comment by alistair3149** [comment]
Should be fixed in [0f4345](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/commit/0f4345dd35e669a224f0fad2ec894853bcf327d0).
