### ISSUE TITLE
Page tools and edit buttons lack RTL styles

### ISSUE THREAD

**Issue by diablo6006** [StarCitizenTools/mediawiki-skins-Citizen#171]
## The Problem
edit buttons are not showing well on rtl language.
![rtl editpage](https://user-images.githubusercontent.com/17708182/89933948-e824a000-dc20-11ea-8a6c-729961576010.png)

plus here on content as it renders behind the text
![rtl editpage 2](https://user-images.githubusercontent.com/17708182/89934103-2326d380-dc21-11ea-8d9b-e67eb48cd500.png)

**Comment by alistair3149** [comment]
Thanks for the report! I'll have a look!

**Comment by diablo6006** [comment]
this issue can be addressed by replacing this: 
`#mw-content-text .mw-parser-output .mw-editsection {
    position: absolute;
    display: flex;
    margin: 0;
    transform: translateX(calc(-100% - 20px));
    right: 0;
}`
with this :
`#mw-content-text .mw-parser-output .mw-editsection {
    position: absolute;
    display: flex;
    margin: 0;
    transform: translateX(calc(-100% - 20px));
    left: 0;
}`

**Comment by alistair3149** [comment]
The page tool were redone recently, is this issue still relevant?

**Comment by diablo6006** [comment]
page tools are good now.
