### ISSUE TITLE
Consider adding a purge page button to the action menu

### ISSUE THREAD

**Issue by diablo6006** [StarCitizenTools/mediawiki-skins-Citizen#172]
## The Problem
can you add a purge-action link to the dropdown menu, just after, move or protect?
![purge-action2](https://user-images.githubusercontent.com/17708182/89934648-f3c49680-dc21-11ea-8069-3080120a5872.png)

![purge-action](https://user-images.githubusercontent.com/17708182/89934470-ad6f3780-dc21-11ea-9ae6-77a881e88345.png)

**Comment by alistair3149** [comment]
I'll look into it! Thanks for the feedback!

**Comment by alistair3149** [comment]
The feature is implemented in [Extension:Purge](https://www.mediawiki.org/wiki/Extension:Purge) and [Semantic MediaWiki](https://www.semantic-mediawiki.org/wiki/Semantic_MediaWiki) already so closing it now
