### ISSUE TITLE
hover effect on images doesn't looks good

### ISSUE THREAD

**Issue by diablo6006** [StarCitizenTools/mediawiki-skins-Citizen#173]
## The Problem
when you hoover some pictures, especially those loaded from commons, you get this hover effect on some of them, which makes it ugly, try to keep this effect on text links only (it a brilliant idea for those hover effects on text links).

Note: this should be done to avoid editing all articles that contain images like those, and there is a lot of them.

one more enhancement, if you could contain gallery images within the same article or body width, and avoid starching it too wide.

![image-hover](https://user-images.githubusercontent.com/17708182/89997232-ef898f00-dc9c-11ea-95ea-73935c1825b7.png)

**Comment by alistair3149** [comment]
The image hovering is a bug that is getting addressed in a hotfix.
As for the gallery image, it is an intended feature but I will look into it in the rework.

**Comment by alistair3149** [comment]
The image bug should be fixed in [d5296a](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/commit/d5296aa267b2a66e2fdd9e6362f348b3189b5a95) in the master and REL1_31 branches now.

**Comment by diablo6006** [comment]
what about REL1_35, the one that I am using

**Comment by alistair3149** [comment]
There isn't a REL1_35 branch, are you using the dev branch? The dev branch is unstable and it is not recommended to use in production.

**Comment by diablo6006** [comment]
I have MediaWiki 1.35 installed, and downloaded the skin from this link :[https://github.com/StarCitizenTools/mediawiki-skins-Citizen/archive/master.zip](url), it seems good so far

**Comment by alistair3149** [comment]
Ah that's the master branch. Closing the issue more since it is fixed.
