### ISSUE TITLE
help, how to do the same footer as presented on starcitizen.tools

### ISSUE THREAD

**Issue by diablo6006** [StarCitizenTools/mediawiki-skins-Citizen#177]
## The Problem
I want to have the same at the footer, how to achieve this?

![footer](https://user-images.githubusercontent.com/17708182/90065300-1f687f00-dcfd-11ea-8cf9-ac373d643699.png)

**Comment by alistair3149** [comment]
You need to define the footer icon on your wiki through the wgFooterIcons in localsettings.php
https://mediawiki.org/wiki/Manual:$wgFooterIcons
