### ISSUE TITLE
Encoded special characters in search suggestion link are flipped when using RTL language

### ISSUE THREAD

**Issue by diablo6006** [StarCitizenTools/mediawiki-skins-Citizen#179]
## Describe the Bug
when searching for mediawiki: your text here, if i click on the search result
This is what i get:
![rtl-search-1](https://user-images.githubusercontent.com/17708182/90308665-5bb10080-def2-11ea-8f07-2bb3d95acf18.png)
<br>
![rtl-search-2](https://user-images.githubusercontent.com/17708182/90308674-6a97b300-def2-11ea-99e7-395bc2504534.png)

1. Change Language to Arabic

2. Create a mediawiki file named: mediawiki:تجربة البحث في الموسوعة
OR: full name in Arabic
(ميدياويكي:تجربة البحث في الموسوعة)

3. Search for the same
4. Click on the result link

I think that the link address has an issue: especially when (%3A) and (%2F) are added or replaced.
قالب%3Aصندوق_معلومات_كائن%2Fنواة

## Expected Behavior
To open the requested page normally, 

## For now
setting $wgCitizenEnableSearch=false; solved the issue by pointing back to mediawiki search, 
![rtl-search-3](https://user-images.githubusercontent.com/17708182/90309136-a3398b80-def6-11ea-8ff3-16c8c9e22ffe.png)

## System
_Please complete the following information:_
 - MediaWiki version [e.g. v1.34.2]
 - Server OS: [e.g. Ubuntu 20.04 LTS]
 - PHP version [e.g. v7.2.19-0ubuntu0.18.04.2]

**Comment by alistair3149** [comment]
Thanks for the report, I'll look into it.

**Comment by alistair3149** [comment]
It seems that the search string was not escaped properly for some reason.
`ميدياويكي:تجربة البحث في الموسوعة` does not work but `MediaWiki:تجربة البحث في الموسوعة` works

**Comment by diablo6006** [comment]
I post it at mediawiki support desk, waiting for some replays

**Comment by diablo6006** [comment]
I got a replay from them,

you need to ensure that things are in the correct byte order: namespace colon pagename. In RTL, the display might be flipped, but it matters what order the text is in, not what order its displayed in. It gets especially confusing when using mixed directionality text.

Note: there is no special redirection for RTL at wikipedia, but there may possibly be alternate namespace translations besides the official ones.

Beyond that, we would need sn actual link to your wiki to say more

Make sure the arabic translstion of the namespace is correct.

[https://www.mediawiki.org/wiki/Topic:Vsshom0zgkc72c18](url)

**Comment by alistair3149** [comment]
@diablo6006 the search suggestion is based on the Wikipedia portal implementation so it should work for RTL wikis on Wikipedia. Bawolff and other folks over at MediaWiki would be able to help you as there is not much I can do. I suggest you link this page on the discussion so that the others can have a reference. Other than that, redirects on your wiki might not be set up properly since the link under `/wiki/` should be a MediaWiki 404 page instead of the Apache 404, you might want to mention this in the discussion as well.
