### ISSUE TITLE
Consider preloading font to decrease load time

### ISSUE THREAD

**Issue by diablo6006** [StarCitizenTools/mediawiki-skins-Citizen#180]
## The Problem
please have a look at this screenshot, adding this tag will reduce more than half-second of loading time. 

![fonts](https://user-images.githubusercontent.com/17708182/90311712-13540b80-df0f-11ea-9cc2-3ff5ff199111.png)

## The Solution
Consider using `<link rel=preload>` to prioritize fetching resources that are currently requested later in page load.

**Comment by alistair3149** [comment]
Will look into it.

**Comment by alistair3149** [comment]
Are you able to reproduce this in the latest version?

**Comment by alistair3149** [comment]
No longer relevant since the font faces are refactored quite a while ago. Closing the issue.
