### ISSUE TITLE
Table of Content toggle is hidden on MW1.32+ on smaller viewport

### ISSUE THREAD

**Issue by diablo6006** [StarCitizenTools/mediawiki-skins-Citizen#183]
## The Problem
table of contents not showing at all. and lazy load images not having any effect

**Comment by diablo6006** [comment]
I got error 500, white screen when I tried 1_32 branch

**Comment by alistair3149** [comment]
Hmm I guess I have to redo the cherry pick from sketch then. I'll put up a patch in the end of the week.

**Comment by diablo6006** [comment]
please note it down here once done,

**Comment by alistair3149** [comment]
Should be fixed altogether in the current build
