### ISSUE TITLE
Lazyload images: Improve load time of your wiki and avoid unnecessary image downloads. Require JS. 

### ISSUE THREAD

**Issue by diablo6006** [StarCitizenTools/mediawiki-skins-Citizen#184]
## The Problem
Lazyload images: Improve load time of your wiki and avoid unnecessary image downloads. Require JS. 

What JS do you mean? and how to implement it

**Comment by diablo6006** [comment]
It's already set to true at LocalSettings, I thought that I have to add a sort of script function to my common.js

**Comment by alistair3149** [comment]
> It's already set to true at LocalSettings, I thought that I have to add a sort of script function to my common.js

If that's the case then it should be enabled.
