### ISSUE TITLE
Timed Media Handler styles fail to load

### ISSUE THREAD

**Issue by octfx** [StarCitizenTools/mediawiki-skins-Citizen#348]
https://github.com/StarCitizenTools/mediawiki-skins-Citizen/blob/447c2b077ee1ab73fa7f1b78d4fa9fa4887a1cd6/skinStyles/extensions/TimedMediaHandler/ext.tmh.player.styles.less.less#L1

File has an extra `.less` in its name

**Comment by alistair3149** [comment]
Fixed in master
