### ISSUE TITLE
Regression: Clicking on the open drawer doesn't close it

### ISSUE THREAD

**Issue by RogerDodger** [StarCitizenTools/mediawiki-skins-Citizen#354]
Prior to [8129ca](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/commit/8129ca0e5ba232ea0866a103c886b6cbffd91a8a), clicking on the drawer would close it.

If this was done to avoid the drawer closing when a link is clicked, checking Event.target in the click handler for anchor elements and not closing the drawer if they're found should address that without causing this regression.

**Comment by alistair3149** [comment]
It is a known issue. The overlay menu is going to be refactored to be less obstructive and sized according to the content, so it won't be needed anymore.

**Comment by alistair3149** [comment]
The overlay menu is changed to a modal in b72ea76. Clicking outside should close the drawer properly now. Would you mind to confirm it?

**Comment by RogerDodger** [comment]
Looks good.
