### ISSUE TITLE
Regression: Can't use `position: sticky` again

### ISSUE THREAD

**Issue by RogerDodger** [StarCitizenTools/mediawiki-skins-Citizen#356]
ed1b55ce450e448ba3f6bf5be872e479444e9d2d re-introduced overflow rules to containers, which presents the same problem noted in #267.

If there are still rogue elements with negative margins and such causing overflows, I'm not sure re-adding this band-aid every time they pop up is the best approach, because aside from breaking sticky positioned elements, it makes it harder to track down and fix said rogue elements.

In either case, an easy solution is using the new `overflow: clip` rule instead, which was created to fix exactly this problem. It works in [Chrome/Firefox/Edge](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow#browser_compatibility) currently, and you can use`overflow: hidden` as a fallback, e.g. `.selector { overflow: hidden; overflow: clip }`.

**Comment by alistair3149** [comment]
It is put in place for rogue elements that is not controlled by the skin, such as extensions or the wiki itself. All the elements on the skin are probably sized and don't need the overflow rules. A better approach maybe putting the overflow rule to `.mw-body-content`, but that might not fix the `position: sticky` issue.

As for the overflow rule, I can add it but note that it has a low support rate and it is very likely that most users will not be benefited by it.

https://caniuse.com/mdn-css_properties_overflow_clip

**Comment by alistair3149** [comment]
It is not a perfect solution but it should be mostly tackled with 6f7f548680a38a7096b5d00faf337ab6bf65f9b7. Closing it for now.
