### ISSUE TITLE
Problem displaying the search box in right-to-left languages

### ISSUE THREAD

**Issue by eshagh79** [StarCitizenTools/mediawiki-skins-Citizen#360]
Hello.
When click in the search box, The magnifying glass symbol(🔎) in Persian (right to left) is not displayed correctly.

Is shown in the attached image.
![Screenshot_2021-05-04 ترجیحات - ویکی شخصی من](https://user-images.githubusercontent.com/52137191/116927142-830e5000-ac70-11eb-8e24-72d570fa74d8.png)
![Screenshot from 2021-05-04 00-28-02](https://user-images.githubusercontent.com/52137191/116927184-90c3d580-ac70-11eb-96c3-15a68b5dc5cb.png)

I solved this problem and sent you a pull request.

Please check it.
![Screenshot_2021-05-04 ترجیحات - ویکی شخصی من(1)](https://user-images.githubusercontent.com/52137191/116927227-a20ce200-ac70-11eb-85e1-55cd29f60fd7.png)

## System
 - MediaWiki version [e.g. v1.35.2]
 - Server OS: ubuntu 20.04
 - version: latest version 1.7.1, I downloaded from Github this morning

**Comment by alistair3149** [comment]
Hi there! Thanks for the report and the patch. It is merged into master now.
