### ISSUE TITLE
Missing icon and text for addsection action in page tools

### ISSUE THREAD

**Issue by eshagh79** [StarCitizenTools/mediawiki-skins-Citizen#368]
When the page width is less than 720 pixels, the "Create New Section" section disappears. But it can still be clicked
![Screenshot from 2021-05-05 13-47-15](https://user-images.githubusercontent.com/52137191/117121282-9f61d800-ada9-11eb-837f-6bf0763d9338.png)

**Comment by alistair3149** [comment]
Is the button added by an extension or gadget? It is the first time I have seen that button.

**Comment by eshagh79** [comment]
I do not know how it was added but I know I have seen this button in some wiki pages before

![Screenshot from 2021-05-05 17-24-49](https://user-images.githubusercontent.com/52137191/117144645-67698d80-adc7-11eb-8a0e-55927e5df0e3.png)

**Comment by alistair3149** [comment]
> I do not know how it was added but I know I have seen this button in some wiki pages before
> 
> ![Screenshot from 2021-05-05 17-24-49](https://user-images.githubusercontent.com/52137191/117144645-67698d80-adc7-11eb-8a0e-55927e5df0e3.png)

Thanks. I'm working on a fix now.

**Comment by alistair3149** [comment]
Added icon and text for the add section action button, would you mind to verify if the issue still persists?

**Comment by eshagh79** [comment]
Now it is displayed correctly.
