### ISSUE TITLE
Hidden "Special Characters" panel in VE toolbar in small viewport

### ISSUE THREAD

**Issue by eshagh79** [StarCitizenTools/mediawiki-skins-Citizen#369]
When editing a wiki page, special characters disappear when the page width is less than 801 pixels.

![Screen Shot 2021-05-06 at 15 59 55](https://user-images.githubusercontent.com/52137191/117136744-0b4e3b80-adbe-11eb-96ef-acb62987860b.png)

**Comment by alistair3149** [comment]
Will look into it.

**Comment by alistair3149** [comment]
Would you mind to verify if you can reproduce the issue with the latest master?

**Comment by eshagh79** [comment]
The problem still persists for me and special characters are not displayed on small pages

**Comment by alistair3149** [comment]
I can't reproduce it on my end anymore with different browsers. Have you clear both server-side and client-side cache on your wiki?
