### ISSUE TITLE
Problem displaying "actions-more" button in source editor

### ISSUE THREAD

**Issue by eshagh79** [StarCitizenTools/mediawiki-skins-Citizen#372]
This is a small problem.

The distance between the more actions button and the visual editor button is short

![Screenshot from 2021-05-06 10-34-03](https://user-images.githubusercontent.com/52137191/117254291-7864de00-ae5d-11eb-8496-27eb60c4aed7.png)

This problem exists in both right-to-left and vice versa

**Comment by eshagh79** [comment]
I think this problem is because of this class:

`#p-views #ca-ve-edit > a {
	padding-left: 16px;
	margin-left: -12px;
}`
Or maybe
`#p-views #ca-ve-edit > a {
	padding-right: 16px;
	margin-right: -12px;
}`

Of course, in right-to-left languages, all right and left are swapped.

**Comment by eshagh79** [comment]
This problem was fixed in my browser by deleting this class.

**Comment by alistair3149** [comment]
Will look into it
