### ISSUE TITLE
VE toolbar overlapping with skin header in small viewport

### ISSUE THREAD

**Issue by eshagh79** [StarCitizenTools/mediawiki-skins-Citizen#373]
When editing an article, when the page width is small, the article editor header merges with the main wiki header.

On pages with large widths, the main header has a background color that prevents this from happening, but on pages with small widths
![Screenshot from 2021-05-06 11-59-36](https://user-images.githubusercontent.com/52137191/117259411-40609980-ae63-11eb-9193-3b5b43f51e6a.png)
![Screenshot from 2021-05-06 11-53-00](https://user-images.githubusercontent.com/52137191/117259415-40609980-ae63-11eb-8d06-ad59db571cbb.png)
![Screenshot from 2021-05-06 11-52-50](https://user-images.githubusercontent.com/52137191/117259431-42c2f380-ae63-11eb-822d-77d27af5bf55.png)

Of course, I still do not know the main reason for this, but I have encountered this several times.

**Comment by alistair3149** [comment]
Will look into it

**Comment by eshagh79** [comment]
What do you think about the photo below?
First open an article with Visual Editor and then press the Menu button and then scroll down

![Screenshot from 2021-05-10 20-17-51](https://user-images.githubusercontent.com/52137191/117687282-e3e7dc00-b1cc-11eb-947d-bd582c5feacc.png)

**Comment by eshagh79** [comment]
I think the previous problem can be solved by adding a background color to the header.

**Comment by alistair3149** [comment]
Just to verify again, what is the exact issue?

**Comment by alistair3149** [comment]
The issue should have been fixed a while ago.
And it is no longer relevant to Citizen 2.X because there are no fixed header.
