### ISSUE TITLE
The ">" sign is pale

### ISSUE THREAD

**Issue by eshagh79** [StarCitizenTools/mediawiki-skins-Citizen#375]
When editing an article, displays ">" instead of "Save Changes" when the page width is short.

The ">" sign is displayed well in the dark but not properly displayed in the light .
![Screenshot from 2021-05-06 21-23-58](https://user-images.githubusercontent.com/52137191/117337632-da9bfe00-aeb2-11eb-812a-cd970f36857c.png)

**Comment by eshagh79** [comment]
This is due to the white background color, which is set in lines 213 to 222 of the file "/skinStyles/extensions/VisualEditor/ext.visualEditor.less"

I could have fixed it, but I thought you would not accept the pull request I sent again 😞

**Comment by eshagh79** [comment]
However, it can be solved to some extent by changing the code 

`background: #fff;`
 to 
`background: var(--background-color-icon);`
![Screenshot_2021-05-06 در حال ویرایش صفحهٔ اصلی - ویکی شخصی من](https://user-images.githubusercontent.com/52137191/117340496-3025da00-aeb6-11eb-989e-0b2c8314ea4d.png)

Still, it doesn't look very good

**Comment by alistair3149** [comment]
> This is due to the white background color, which is set in lines 213 to 222 of the file "/skinStyles/extensions/VisualEditor/ext.visualEditor.less"
> 
> I could have fixed it, but I thought you would not accept the pull request I sent again 😞

Yeah it is missing proper color for the disabled state. And no I have been merging PRs after they are tested.

**Comment by alistair3149** [comment]
> Hello.
> I pull request the above solution.
> But it still doesn't look good. A slightly better solution is to use RGB color instead of RGBA color for the icon.
> And better yet, use an SVG icon.
> https://github.com/FortAwesome/Font-Awesome/blob/master/svgs/solid/angle-right.svg
> I found this icon in fontawesome. Its size is 450 bytes.

It needs a different color in the disabled state.
As for SVG, I don't know any performant way to selectively load SVG based on MediaWIki ResourceLoader modules loaded, if someone can guide me I would be glad to switch everything to SVGs.

**Comment by alistair3149** [comment]
I added a patch that should somewhat mitigate the issue. The other issue that you mentioned with transparency will be solved in the future when I rework all the colors used in the skin.
