### ISSUE TITLE
Citizen-specific JavaScript is loaded for all skins

### ISSUE THREAD

**Issue by Yuubari** [StarCitizenTools/mediawiki-skins-Citizen#376]
## Describe the Bug
With the Citizen skin loaded in LocalSettings.php, https://github.com/StarCitizenTools/mediawiki-skins-Citizen/blob/master/includes/Hooks/SkinHooks.php#L65 applies theme selection JS (including font size and page width) when the current active skin is not Citizen, which, for example, alters the root element (with Vector being the currently active skin):
```html
<html class="client-js skin-citizen-light ve-available" dir="ltr" style="font-size: 16px; --width-layout:960px;" lang="en-GB">
```
This change does not happen if Citizen was not used previously (with its properties in local storage unset). Previewing via `?useskin=citizen` is enough to trigger this DOM change.

1. Have several skins available.
2. Use Citizen, then switch to a different skin.
3. The page will have `skin-citizen-…` present in its root element class list.

## Expected Behavior
With a different skin selected, no Citizen-specific code should (probably) be loaded.

## System
 - MediaWiki version: 1.35.2
 - Server OS: FreeBSD 13.0-RELEASE
 - Installed extensions and versions: ConfirmUserAccounts, SimpleBatchUpload 1.7.0, TemplateSandbox 1.1.0, WikiSEO 2.5.0, OpenGraphMeta 0.5.5, Tabber 2.4.5, TemplateStyles 1.0, Cargo 2.7, CirrusSearch 6.5.4, etc.
 - PHP version: PHP 7.4.16 (cli) (built: Apr 15 2021 17:41:30) ( NTS )

**Comment by alistair3149** [comment]
Thanks for the report! I released a patch on the master branch. Would you mind to check if you can reproduce the issue?

**Comment by Yuubari** [comment]
Thank you; it appears to be fixed.
