### ISSUE TITLE
Do not show the logo

### ISSUE THREAD

**Issue by eshagh79** [StarCitizenTools/mediawiki-skins-Citizen#378]
I am using Firefox 88 on Ubuntu 20.04.
The problem is that the site logo is not displayed in the menu.
The same is true in Opera browser.

This problem is very strange because everything seems to be right.
Because it should be hidden only for pages smaller than 800 pixels, but now it is hidden for all pages
![Screenshot from 2021-05-10 20-31-59](https://user-images.githubusercontent.com/52137191/117689613-2f9b8500-b1cf-11eb-8da6-6395d794ced5.png)
![Screenshot from 2021-05-10 20-32-09](https://user-images.githubusercontent.com/52137191/117689850-6b364f00-b1cf-11eb-8711-2d880c094b16.png)

**Comment by alistair3149** [comment]
The logo is hidden on pages shorter than `800px` in height to allow more space for navigation menu.

**Comment by eshagh79** [comment]
I know.
But it is also hidden on pages larger than 800 pixels
