### ISSUE TITLE
Visual Editor - reference editing pop-up dialogues empty

### ISSUE THREAD

**Issue by MrSmith35** [StarCitizenTools/mediawiki-skins-Citizen#385]
Hi, 
I've just installed MediaWiki on my Synology NAS and got it working well. Installed Citizen as my preferred skin - great work by the way. The Wiki I'm running is purely for personal use, pages will contain a lot of references/footnotes. At the moment I am using the basic Cite system for references, no other Cite extensions yet. The only customisation of Citizen that I've made is a general css parameter to make normal tables - not wikitables - have fine borders - 'border-collapse: collapse;'  - which works without issue. 

So in _Visual Editor_ I should be able to click on a reference number in the article text - they look like **[4]** for example - and a dialogue opens where I can read the reference. The problem is that the dialogue is empty, or rather the text is somewhere off to the right in a long, single letter column, effectively unreadable. Clicking the actual edit button in this dialogue brings up a pop-up where I should be able to edit the text of the reference, however the text is again somewhere off to the right.

I tried a clean installation of Citizen, but the same happens. What I have discovered is that this only seems to affect desktop browser windows. On my iPad (iOS 14.5.1) in Safari and Brave (1.25) (Chrome) editing the references work as expected, but in desktop browsers - Safari (13.0.5), Brave (1.24.85 Chromium 90.0.4430.212) both on MacOS 10.14.6; Windows Edge, Chrome and Firefox on Windows 10 - the issue occurs. BUT if I reduce the browser window width to something similar to a tablet or phone, the issue goes away.

I also tried this with the default skin (Vector), Metrolook and Chameleon, none have this problem.

Thanks

## System

 - MediaWiki version 1.35.2
 - Server OS: DSM 6.2.4-25556 on Synology DS918+
 - PHP version 7.4.9

 - **Installed extensions and versions:**
 - **Special pages**
 - CiteThisPage n/a
 - SimpleBatchUpload 1.8.2
 - 
 - **Editors**
 - CodeEditor n/a
 - VisualEditor 0.1.2
 - WikiEditor 0.5.3
 - 
 - **Parser hooks**
 - CategoryTree n/a
 - Cite n/a
 - ImageMap n/a
 - InputBox 0.3.0
 - ParserFunctions 1.6.0
 - SyntaxHighlight 2.0
 - TemplateData 0.1.2
 - 
 - **Media handlers**
 - PDF Handler n/a
 - 
 - **Other**
 - Bootstrap 4.5.0
 - Gadgets n/a
 - MultimediaViewer n/a
 - TextExtracts n/a

**Comment by alistair3149** [comment]
Thanks for the report! Would you mind to check if the latest patch fix the issue for you?

**Comment by MrSmith35** [comment]
> Thanks for the report! Would you mind to check if the latest patch fix the issue for you?

Yep, no problem, will do it later tonight. Thanks for your quick response!

**Comment by MrSmith35** [comment]
That works great now. Thanks
