### ISSUE TITLE
Versions/Releases?

### ISSUE THREAD

**Issue by berot3** [StarCitizenTools/mediawiki-skins-Citizen#389]
## The Problem
It's a bit too hard to find what the current version of the skin is.

## The Solutions

- [create releases on GitHub](https://docs.github.com/en/github/administering-a-repository/managing-releases-in-a-repository#creating-a-release)
- add [version-field](https://www.mediawiki.org/wiki/Template:Skin/de#version) to the [Mediawiki-page](https://www.mediawiki.org/wiki/Skin:Citizen)

## The Alternatives
Of course one can also look into [skin.json](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/blob/master/skin.json)

**Comment by alistair3149** [comment]
The skin is in continuous update so the version is mainly used to track bug fixes or breaking changes. I might start to mark release tag when I set up a way to generate changelog automatically.

**Comment by alistair3149** [comment]
Tagging releases from now on on GitHub
