### ISSUE TITLE
Use of User::isLoggedIn was deprecated in MediaWiki 1.36

### ISSUE THREAD

**Issue by jdlrobson** [StarCitizenTools/mediawiki-skins-Citizen#395]
## Describe the Bug

Seen on https://skins-demo.wmflabs.org/w/index.php?useskin=citizen with deprecation warnings enabled (let me know if you need help reproducing)

```
( ! ) Deprecated: Use of User::isLoggedIn was deprecated in MediaWiki 1.36. [Called from Citizen\Partials\Header::buildPersonalMenu in /vagrant/mediawiki/skins/Citizen/includes/Partials/Header.php at line 62] in /vagrant/mediawiki/includes/debug/MWDebug.php on line 376
Call Stack
#TimeMemoryFunctionLocation
10.0002397848{main}(  ).../index.php:0
20.0016403648require( '/vagrant/mediawiki/index.php' ).../index.php:5
30.17385369968wfIndexMain(  ).../index.php:46
40.17385372096MediaWiki->run(  ).../index.php:53
50.17435372352MediaWiki->main(  ).../MediaWiki.php:559
60.50917245584MediaWiki::{closure:/vagrant/mediawiki/includes/MediaWiki.php:937-943}(  ).../MediaWiki.php:952
70.50917245584OutputPage->output(  ).../MediaWiki.php:939
80.53817427576SkinCitizen->outputPage(  ).../OutputPage.php:2644
90.55267441768SkinCitizen->generateHTML(  ).../SkinTemplate.php:147
100.55417450312SkinCitizen->getTemplateData(  ).../SkinMustache.php:137
111.10038313920Citizen\Partials\Header->buildPersonalMenu(  ).../SkinCitizen.php:108
121.10328316968User->isLoggedIn(  ).../Header.php:62
131.10328316968wfDeprecated(  ).../User.php:2970
141.10328316968MWDebug::deprecated(  ).../GlobalFunctions.php:998
151.10338317064MWDebug::deprecatedMsg(  ).../MWDebug.php:230
161.10338318632MWDebug::sendRawDeprecated(  ).../MWDebug.php:352
171.10358318632trigger_error
(  ).../MWDebug.php:376
```
## Expected Behavior

No deprecation warning.

## System
_Please complete the following information:_
 - MediaWiki version v1.36 (current master)
 - Server OS: [e.g. Debian 10]
 - Installed extensions and versions [e.g. SemanticMediaWiki 3.0, WikiSEO 2.3.1, etc.]
 - PHP version [e.g. v7.2.19-0ubuntu0.18.04.2]

**Comment by alistair3149** [comment]
It is not used anymore in the current main branch. It seems that the skin on the skinlab on an old version (1.7.2). Please let me know if updating it fix the issue!

**Comment by jdlrobson** [comment]
Ah I see what's happening. MediaWiki's Vagrant appears to be assuming that the skins are using the old origin/master branch, but Citizen uses the origin/main branch... Looking..

**Comment by jdlrobson** [comment]
Awesome. Okay that shouldn't happen again. Sorry about that!

**Comment by alistair3149** [comment]
Sorry about that. I thought GitHub would have redirected the master branch back to the main branch :(
