### ISSUE TITLE
Footer opposite color when changing theme through cog menu

### ISSUE THREAD

**Issue by forteller** [StarCitizenTools/mediawiki-skins-Citizen#397]
## Describe the Bug

Hi again. Same wiki and system as last time (#396, norskpolitikk.miraheze.org)

Description in title

1. Change from Dark to either Light or Auto trough the menu in the cog in the upper right hand
2. Notice that the page switches from dark to light background.
3. Scroll down to the footer and either notice that it is still dark, or click on the dark/light mode link and notice how the footer is the opposite of the rest of the page. Every time you click dark/light mode in the footer the page gets one color and the footer the other.
4. Switch back to Dark trough the cog
5. Click on dark/light mode in the footer again and notice how both page and footer has the same color

## Expected Behavior
Page and footer should always keep the same color, either both dark or both white at the same time.

Thank you again!

**Comment by alistair3149** [comment]
Hi there! The footer actually have a fixed dark color at the moment. I am implementing a more flexible color system and will get to the footer color in the process.

**Comment by forteller** [comment]
Ok. As long as you're aware and will fix it at some time, it's not very important to me when it happens. I just can't code myself, and want to help in the way I can: Filing bugs :)

**Comment by alistair3149** [comment]
The footer is reworked as a part of the Citizen 2.X update. It should be theme-aware now:
![image](https://user-images.githubusercontent.com/9260542/193424962-afc0911f-a0bd-45f8-8617-ce1d72548b9e.png)
