### ISSUE TITLE
Broken articles in mobile view

### ISSUE THREAD

**Issue by forteller** [StarCitizenTools/mediawiki-skins-Citizen#409]
Hi. First off: Love this skin so much! Thank you for your work!

## Describe the Bug

Whenever I visit any of the articles on my wiki using Citizen on a phone/in mobile view, I can only see the name of the headers of each section. You're seemingly supposed to be able to tap the headings to expand them and see the text, but that does not work. There are some arrows changing direction, and that's it.

A screenshot from this article: https://norskpolitikk.miraheze.org/w/index.php?title=Organisasjoner&mobileaction=toggle_view_mobile

![Screenshot from 2021-11-13 18-04-27](https://user-images.githubusercontent.com/343561/141652754-576f4507-02cd-4735-b5b1-c69398663900.png)

This means that the wiki is totally unusable on phones.

1. Go to an article with headings in mobile view
2. Click/tap the headings and notice that they don't expand

## Expected Behavior
Tapping the headings should expand them so you can read the content.

## System
 - MediaWiki version: 1.36
 - Citizen version: 1.10.0 (26cfa2d)
 - Server OS: Sorry, I'm not sure
 - Installed extensions and versions: Please find a list here, under "Installerte utvidelser" https://norskpolitikk.miraheze.org/wiki/Spesial:Versjon
 - PHP version: 7.3.31-1~deb10u1 (fpm-fcgi)

Thank you!

**Comment by forteller** [comment]
Sorry! It was because of the MediaWiki extension MobileFrontend. Thanks for the Miraheze people for helping me figure it out.

**Comment by alistair3149** [comment]
This should be fixed from the recent patch. Now you can use MobileFrontend together with Citizen if you decide.
