### ISSUE TITLE
Some icons are missing

### ISSUE THREAD

**Issue by Inui-senpai** [StarCitizenTools/mediawiki-skins-Citizen#412]
## Describe the Bug
Not sure if this a bug, but some icons was disappeared after reinstalling an OS on server and restoring wiki from backup: Help icon in 
Special pages' headers and checkmark in the successful edit popup:
![Snap7684](https://user-images.githubusercontent.com/29918546/144208034-b04c360f-3aca-48e3-ae3c-fd6f20bef685.png)
![Snap7685](https://user-images.githubusercontent.com/29918546/144208038-7d1213e6-9121-4eee-9beb-efdd4dbd28f1.png)
But the icon image is loaded (status 200), judging by the Network tab of the Dev Tools, although it classified as "text/plain" instead of "svg+xml":
![Snap7687](https://user-images.githubusercontent.com/29918546/144217689-8050103c-19cf-4f72-87ea-1122ddcc8399.png)
But one way or another, this image is present in the specified directory and I can even download it and open it afterwards:
![Snap7688](https://user-images.githubusercontent.com/29918546/144218804-3ce289d3-cbf0-4913-bf87-da280ecff885.png)
![Snap7689](https://user-images.githubusercontent.com/29918546/144218899-d172e6d6-877e-4172-8d29-bf344cdbea0e.png)
I also tried to update the MediaWiki, but to no avail.
All necessary packages are installed, although I don't deny that I might have missed something.

And one more thing: if I write all the contents of the particular SVG file instead of path in the `background-image` variable of the according `.less` file, icon will display correctly:
![Snap7690](https://user-images.githubusercontent.com/29918546/144225176-6124330a-1c6b-4b95-948b-bbe8051f0603.png)

Skin was downloaded as source code from the main branch yesterday.

1. Open Menu and click on "Special Pages"
2. Look at the opened Special Page's header
3. For the second error, open any article and edit it via Visual Editor, then click on "Save changes" and look at the top of page

## Expected Behavior
Displayed Help icon on the left of the "Help" button and displayed green checkmark in the Visual Editor's popup.

## System
 - MediaWiki version: 1.37.0 (before update - 1.36.2)
 - Server OS: Debian 11
 - Installed extensions and versions:
- Editors:
CodeEditor
VisualEditor (0.1.2)
WikiEditor (0.5.3)
- Parser Hooks:
CategoryTree
Cite
EmbedVideo (2.8.0)
ParserFunctions (1.6.0)
SyntaxHighlight (2.0)
TemplateData (0.1.2)
- Other:
LocalisationUpdate (1.4.0)
MultimediaViewer
Purge (2.0.0)
 - PHP version: 7.4.25 (fpm-fcgi)

**Comment by alistair3149** [comment]
Those icons are not a part of the skin. I have no idea what could possibly cause those issues :(

**Comment by Neko-Monika** [comment]
I understand. Well, I'll keep thinking. 🤔

**Comment by Neko-Monika** [comment]
Tried to convert "problematic" SVGs to PNG (via Greenfish Icon Editor Pro) and correct its mentions in according files, and it seemed to work:
![Snap7704](https://user-images.githubusercontent.com/29918546/144488998-3f4818a2-e4cd-4b46-898a-0d79090a2f26.png)
![Snap7705](https://user-images.githubusercontent.com/29918546/144489001-ae85e004-ca82-4865-871a-ea8b84679ddf.png)
By the way, external link icon (it was loaded from "skins.citizen.styles" folder, judging by the Network tab) was disappeared too (didn't screenshot that, sorry), so I "fixed" this icon too:
![Snap7706](https://user-images.githubusercontent.com/29918546/144489345-0f4c67c6-af62-42ff-9819-155b23891900.png)

You may want to do the same thing with the mentioned icons and include it in the skin. SVG has always been a pain in the ass, in my opinion.

**Comment by alistair3149** [comment]
Hmm it seems that there are something wrong with the installation since SVGs are used in Vector too. I don't know how to troubleshoot that unfortunately.

**Comment by alistair3149** [comment]
Icons in the issue are not related to the Citizen skin but MW core. Closing the issue.

**Comment by MarcPelland** [comment]
Icons in the Vector 2022 header weren't displaying on my wiki either. I had a blank first line in my LocalSettings.php. Once I deleted that line, the icons came back.
