### ISSUE TITLE
Light/dark not work in 1.35.5

### ISSUE THREAD

**Issue by qw918** [StarCitizenTools/mediawiki-skins-Citizen#414]
## Describe the Bug

No matter what mode is set, when you open a new page, the page will be light mode, and then it will be dark mode, and if you manually select it on the page, you can change it to light mode, but the footer is still dark. 

## System
MediaWiki	1.35.5
PHP	7.4.27 (apache2handler)
MySQL	5.7.9
ICU	67.1
Lua	5.1.5

**Comment by alistair3149** [comment]
Thanks for the report! Will look into it.

**Comment by alistair3149** [comment]
Should be fixed by 047f830d1a992313ed871bce3980a6b65ef04d1b
