### ISSUE TITLE
$wgCitizenThemeDefault does not appear to be working

### ISSUE THREAD

**Issue by Chevron9** [StarCitizenTools/mediawiki-skins-Citizen#418]
## Describe the Bug
Setting `$wgCitizenThemeDefault = 'dark';` does not appear to actually set the default theme to dark, instead, the skin continues to operate with 'auto' as per default.

## System
MediaWiki | 1.37.1
PHP | 7.4.27 (apache2handler)

**Comment by alistair3149** [comment]
Sorry for the late response. It should be fixed recently. Would you mind to check if it is fixed?

**Comment by Chevron9** [comment]
It does not seem to be working. I'm not 100% sure I've tested it correctly - the site in question is https://delta-v.kodera.pl/index.php/Main_Page

**Comment by alistair3149** [comment]
> It does not seem to be working. I'm not 100% sure I've tested it correctly - the site in question is https://delta-v.kodera.pl/index.php/Main_Page

There are some changes related to this a few patches ago. Would you mind updating the skin and try again?
