### ISSUE TITLE
buildContentNavigationUrls is deprecated in 1.38

### ISSUE THREAD

**Issue by jdlrobson** [StarCitizenTools/mediawiki-skins-Citizen#422]
## Describe the Bug
We're deprecating buildContentNavigationUrls in 1.38
This is foundation work for simplifying and finally improving menu code in MediaWiki core, so skins can have more control over menu data generation.

1. Use latest MediaWiki master
2. Load Citizen
3. Check error logs for deprecation notice

## Expected Behavior
I'll provide a short term fix for this.

On the long term I suggest moving Citizen towards using the data provided by `Skin::getTemplateData()`. I'm working us towards a data array instead of a blob of HTML for representing the menu so any feature requests you have around the format in getTemplateData would be greatly appreciated.

**Comment by alistair3149** [comment]
Thanks for the PR. Is it a hard depreciation or a soft one? We have to maintain LTS compatibility so if it can't be backported to 1.35 then we might have to revisit it later.

**Comment by jdlrobson** [comment]
I've updated the patch so that it works on all MediaWiki versions >= 1.35.
