### ISSUE TITLE
Some Javascript features sometimes fail to load

### ISSUE THREAD

**Issue by lachlanshanks** [StarCitizenTools/mediawiki-skins-Citizen#432]
## Describe the Bug
If I load several pages at the same time, one or two often don't have the cog wheel and the search suggestions do not appear on these pages. I'm not sure what is causing this. I have removed site-wide and skin Javascript.

1. Go to https://coasterpedia.net.
2. Try loading several pages
3. One or two pages loaded may have this problem

## System
_Please complete the following information:_
 - MediaWiki version 1.37
 - Server OS: Linux
 - Installed extensions and versions [[e.g. SemanticMediaWiki 3.0, WikiSEO 2.3.1, etc.]](https://coasterpedia.net/wiki/Special:Version)
 - PHP version 7.3.22

**Comment by ChaoticShadow** [comment]
I'm having a similar issue but don't know if it's caused by the same thing.

For me, whenever the cog doesn't show up, I get an error in the console saying "TypeError: checkbox is null"

**Comment by lachlanshanks** [comment]
> I'm having a similar issue but don't know if it's caused by the same thing.
> 
> For me, whenever the cog doesn't show up, I get an error in the console saying "TypeError: checkbox is null"
I get the same error on Coasterpedia. What wiki are you looking at? I haven't noticed this on the Star Citizen Wiki, I'm not sure what they're doing differently.

**Comment by ChaoticShadow** [comment]
I'm over at [Project Sekai Wiki](https://projectsekai.miraheze.org/wiki/Main_Page), using Citizen v1.10.0. We're hosted by Miraheze so I'm not too clear on the update timeline but this issue seems to have existed since we started using the skin.

Star Citizen Wikis seem to be using 1.9.4 on English and 1.10.0 on German. If the cog is sometimes gone on the German wiki then it might be a bug that got introduced from 1.9 => 1.10?

**Comment by alistair3149** [comment]
Yeah that's the JavaScript loading issue that I have been scratching my head on. I wasn't able to locate the exact cause of it but it does happen from time to time even in the 1.9.X version used on Star Citizen Wiki. I'll be refactoring the skin for MW 1.39 and hopefully it'll somehow go away, or else I'm really clueless about this one.

**Comment by ChaoticShadow** [comment]
I know this was closed a couple days ago, but it looks like the issue still persists. For reference, Miraheze just updated Citizen to 1.14.1 (0f38149).

![image](https://user-images.githubusercontent.com/6554395/166083133-f6efaf6d-ece5-481f-ba31-0b89c494cac2.png)

**Comment by alistair3149** [comment]
It could be a caching issue, I'll continue to track it for a week to see if I can find anything new.
