### ISSUE TITLE
Have Discussion link visible at all times

### ISSUE THREAD

**Issue by lachlanshanks** [StarCitizenTools/mediawiki-skins-Citizen#436]
The discussion link is currently hidden within the page tools drop down. Personally I'd prefer it if it were immediately visible beside the History and Edit links. Getting users to discuss is hard enough as it is so I think the extra visibility of the button would be beneficial.

**Comment by alistair3149** [comment]
Looking into it! 
My plan was to move the discussion button to where history is but it can get crowded considering different languages and also the amount of buttons there. So I am back to the drawing board and looking for more ideas. If anyone is interested in helping out, please feel free to comment or submit a patch if you like!

**Comment by lachlanshanks** [comment]
This is a problem I've thought about before and been unsure what the best approach is. I like how in Vector and Monobook the discussion/article are tabs, but that would require even more space still. 

My coding experience is (very) limited but I've managed to edit our version of Citizen such that the discussion button is always visible. But it's not the solution you're looking for. I'm planning to have the skin be wider by default which somewhat negates the space issue.

**Comment by alistair3149** [comment]
The namespace links (e.g. Discussion) are now added next to the view links (e.g. Edit) (37beda8e87559cffad4b21f4108708451c00ccee).
It is a bandage fix that I will revisit later, since I want to add discussion count and also refactor the language menu alongside with it. But now it should be sufficient to close this issue.
