### ISSUE TITLE
Add support for Wikibase

### ISSUE THREAD

**Issue by shigapov** [StarCitizenTools/mediawiki-skins-Citizen#439]
Thank you for very nice skin! I would like to use it with Wikibase (https://wikiba.se). In general it works fine. Though, some extra work on styling is needed for entity-pages, especially in a dark mode.

**Comment by alistair3149** [comment]
Hi there and thank you! Do you have some example pages where the styles are missing? I wasn't able to get a local version working so it would be helpful!

**Comment by shigapov** [comment]
Hi @alistair3149!

An easy way is to run a dockerized [Wikibase Release Pipeline](https://github.com/wmde/wikibase-release-pipeline/tree/main/test). Just copy `default.env` to `.env`and run `docker-compose -f docker-compose.yml -f docker-compose.extra.yml up -d --scale wikibase_jobrunner=1`.

I have made two screenshots in dark and light modes:
![Screenshot_Dark_Test_item](https://user-images.githubusercontent.com/57352291/167823434-ee50891c-bad1-4c85-9604-03d3e2ce376f.png)
![Screenshot_Light_Test_item](https://user-images.githubusercontent.com/57352291/167823438-5b7d78b7-d882-4606-ae74-c7951e7f233a.png)

**Comment by alistair3149** [comment]
Hi @shigapov,

Unfortunately I wasn't able to get Wikibase set up but I did take a look into the extension. There are a lot of styles and I can't tell what is used where without having a live instance because of the way it is structured. So I did a conversion by looking at the stylesheets (3867f1588afb019eaa157063ad521fd98f133afb). Please let me know if you run into any issues!

**Comment by shigapov** [comment]
It looks much better, thank you! I am attaching the screenshots:

![wiki-dark-mode](https://user-images.githubusercontent.com/57352291/168064319-0d75ad0a-e241-4069-bec8-6b45c526f674.png)
![wiki-light-mode](https://user-images.githubusercontent.com/57352291/168064322-aba282bf-f9e7-4768-ae35-391ef8b7abaa.png)
