### ISSUE TITLE
feat: Import designs of infoboxes from Star Citizen Wiki as SkinStyles for infobox extensions

### ISSUE THREAD

**Issue by lens0021** [StarCitizenTools/mediawiki-skins-Citizen#442]
There are several extensions that provide a way to render infoboxes (PortableInfobox, Cargo, etc) but without SkinStyles from Citizen skin.

And, there are designs & styles for infobox on [Star Citizen Wiki](https://starcitizen.tools/),  ([example on starcitizen.tools](https://starcitizen.tools/Avenger_Stalker) and [example on star-citizen.wiki](https://star-citizen.wiki/Javelin)) it is fancy and fits with Citizen skin.

If the licenses are compatible, using the design will be good.

**Comment by alistair3149** [comment]
Do you have some example pages on infoboxes from PortableInfobox and Cargo?

> If the licenses are compatible, using the design will be good.

The styles are open sourced so feel free to use it. 

My only concern is that the infoboxes on both Star Citizen Wikis are structured a bit differently than the usual infoboxes. On top of that I don't have experience with infoboxes in Cargo and limited experience with PortableInfobox back in Fandom days. So I need to see the use cases to think about how we can approach this.

**Comment by lens0021** [comment]
A PortableInfobox example page is here: https://wordles.miraheze.org/w?curid=10 though its styles are tweaked already.
About Cargo, in honestly I don't have experience too. I saw some wikis using both Citizen and Cargo, but I have not been involved in them. So maybe this task is impossible for now, if then, it is okay for me to close this issue because I'm focusing on PortableInfobox.

**Comment by alistair3149** [comment]
Close due to #443
