### ISSUE TITLE
Unable to tap the "close" button of the new TimedMediaHandler on mobile devices

### ISSUE THREAD

**Issue by AlanYe-Dev** [StarCitizenTools/mediawiki-skins-Citizen#447]
![图片](https://user-images.githubusercontent.com/45558679/166084051-27e757ac-e8ab-40d7-bc6b-7d12cbefe638.png)
TimedMediaHandler works fine on large screens, but on phones, it's not working well

**Comment by alistair3149** [comment]
Do you have a live page that I can check it out?

**Comment by AlanYe-Dev** [comment]
https://sonicpedia.org.cn/wiki/Fading_World
Here's an example
