### ISSUE TITLE
Clicking on auto changes to light mode rather than dark mode in a dark browser

### ISSUE THREAD

**Issue by ZechariahB** [StarCitizenTools/mediawiki-skins-Citizen#461]
## Description
When you click on either dark mode or light mode in preferences, then click on auto. It should revert back to its intended mode according to browser preset, but this is not the case. Auto will always change to light mode until the page is refreshed. Furthermore, reverting settings to default changes auto from dark mode to light mode. `$wgCitizenThemeDefault` is set to `"auto"`

#### Is it reproducible?:
Always. 

## System
- MediaWiki version 1:1.35.4-1+deb11u2
- Firefox version: 91.9.0esr-1~deb11u1
- Operating system: Debian 11
- PHP version: 7.4.28

**Comment by alistair3149** [comment]
Thanks for the report. Will look into it.
