### ISSUE TITLE
WikiEditor toolbar appears above other things like dropdowns

### ISSUE THREAD

**Issue by lachlanshanks** [StarCitizenTools/mediawiki-skins-Citizen#462]
On both desktop and mobile the WikiEditor toolbar appears above the dropdown menus. Its z-index is 7, I'm not sure why. This issue can be fixed by adding 

.wikiEditor-ui-toolbar {
	z-index:1;
}

to MediaWiki:Citizen.css. Presumably could also be fixed by changing the z-index of the various dropdowns in the Citizen skin.

**Comment by alistair3149** [comment]
Thanks for letting me know! I'll look into it tomorrow.
I was cleaning up all the z-index uses but it seems like that extensions don't really use the WMUI variables.
