### ISSUE TITLE
DiscussionTools doesn't work

### ISSUE THREAD

**Issue by lachlanshanks** [StarCitizenTools/mediawiki-skins-Citizen#463]
DiscussionTools doesn't appear to work with the Citizen skin. You can try adding a new section or replying to a message on my talk page at https://coasterpedia.net/wiki/User_talk:Lachlan?useskin=citizen (you'll need to make an account first).

Looking at the browser Console suggests there is a file missing within the skin.

I'm on MediaWiki 1.37, the latest version of Citizen as of writing, PHP version 8.0.12

**Comment by alistair3149** [comment]
Thanks for the report, it should be fixed by 0a0456db970f4839bc33f60c587f2775b48eb848.
