### ISSUE TITLE
IntlException: Constructor failed with NumberFormatter

### ISSUE THREAD

**Issue by Bleestones** [StarCitizenTools/mediawiki-skins-Citizen#466]
## Describe the Bug
When loading the theme and switching to that theme, I get an error on the web page! On the "Version" page there is the Skin
![image](https://user-images.githubusercontent.com/66253666/170891870-34fa6719-db0b-48af-888b-ae02c5a3bc65.png)

1. Go to Preferences
2. Click on to the Citizen at the Skin
3. Scroll down to the Save button
4. Click on the Save button
5. See error

Working version.: 'c4b9abd5c055a508b6c9b9ff9a02a668adf94fc0' --> [mediawiki-skins-Citizen-main.zip](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/files/8794345/mediawiki-skins-Citizen-main.zip)

## Expected Behavior
The theme, nicely saved
## System
_Please complete the following information:_
 - MediaWiki version : 1.37.2
 - Server OS: Shared hosting
 - Installed extensions and versions : Disabled all of them or enabled the default extensions. (I not installed any, yet)
 - PHP version :  7.4.15 (cgi-fcgi)

**Comment by alistair3149** [comment]
Looking into it.
Just to verify, do you have the PHP intl package?

**Comment by Bleestones** [comment]
`$wgCitizenEnableDrawerSiteStats	= false;` can solve the problem, but I think this is important!
![image](https://user-images.githubusercontent.com/66253666/170936077-3b8f547d-b300-4a7b-b659-8f57e4181958.png)

**Comment by Bleestones** [comment]
Tested on, other hosting with other PHP intl version, and I got the same result!
![image](https://user-images.githubusercontent.com/66253666/170982010-b81456fa-419d-4934-a70c-30f1fa5a32ea.png)
![image](https://user-images.githubusercontent.com/66253666/170982022-62e6a5fb-5294-4c42-8428-86a46f2c06e5.png)
![image](https://user-images.githubusercontent.com/66253666/170982039-654a4a2f-1a4c-47f8-adc3-3256b5193b5d.png)

**Comment by Bleestones** [comment]
At PHP 7.3.33, the error.:
![image](https://user-images.githubusercontent.com/66253666/171025011-92ad48c1-ed2d-4a6f-8120-49e0324648c7.png)

**Comment by alistair3149** [comment]
> At PHP 7.3.33, the error.: ![image](https://user-images.githubusercontent.com/66253666/171025011-92ad48c1-ed2d-4a6f-8120-49e0324648c7.png)

Use the latest main

**Comment by alistair3149** [comment]
It is likely a configuration with php-intl or ICU on your end since the error is related to NumberFormatter itself. Closing it for now

**Comment by Bleestones** [comment]
Solution.: Update the ICU version! Please test the minimum ICU version of this SKIN! Now, at the newest ICU version, it works fine!
