### ISSUE TITLE
Various issues with the skin

### ISSUE THREAD

**Issue by max20091** [StarCitizenTools/mediawiki-skins-Citizen#467]
Somehow the slideshow appears to be extremely small on Citizen skin but not others
![image](https://user-images.githubusercontent.com/12845078/171188339-5bf0c212-5310-4f11-80fa-0cf6d18495e9.png)

And the skin loads bigger image on phones compared to desktop, that issue wasted lots of bandwidth. Tested on my wiki and current Star Citizen Wiki

**Comment by alistair3149** [comment]
> Somehow the slideshow appears to be extremely small on Citizen skin but not others ![image](https://user-images.githubusercontent.com/12845078/171188339-5bf0c212-5310-4f11-80fa-0cf6d18495e9.png)
> 
> And the skin loads bigger image on phones compared to desktop, that issue wasted lots of bandwidth. Tested on my wiki and current Star Citizen Wiki

For the slideshow, does it happen on other skins as well?
As for image size, the skin does not handle image load, it only make sure the image fit inside the viewport. For iPhone SE, which has a pixel density of 2x, the minimum width of that image should be at least 666px, it is not that far off.

**Comment by max20091** [comment]
> For the slideshow, does it happen on other skins as well?

I tested Vector and Timeless skins, both works normally
![image](https://user-images.githubusercontent.com/12845078/171207512-07a55bac-8998-498a-b7e9-6e904aeddcb0.png)

**Comment by alistair3149** [comment]
Looking into it

**Comment by alistair3149** [comment]
The slideshow issue should be fixed now, would you mind to verify it?

**Comment by max20091** [comment]
Is it possible to fix the issue with common.css/js? Currently my wiki is unable to upgrade theme at the moment

**Comment by max20091** [comment]
confirmed fixed, closing
