### ISSUE TITLE
Alerts, notices dropdowns, and Special:Notifications dark mode problems

### ISSUE THREAD

**Issue by lachlanshanks** [StarCitizenTools/mediawiki-skins-Citizen#468]
The username and "view changes" text in the alerts/notices dropdowns and at Special:Notifications are not readable in dark mode as the text doesn't go light. Also, the loading area and background of Special:Notifications stays light, it should change to dark in dark mode.

The issue is present on both Coasterpedia and Star Citizen Wiki.

**Comment by alistair3149** [comment]
Thanks for the report! It should be fixed shortly
