### ISSUE TITLE
Exception in module skins.citizen.scripts:

### ISSUE THREAD

**Issue by octfx** [StarCitizenTools/mediawiki-skins-Citizen#475]
## Describe the Bug
After upgrading Citizen to `1.17.5`, I'm seeing an exception when typing into the search box.

```
TypeError: Cannot read properties of null (reading 'addEventListener')
    at initCheckboxHack (<anonymous>:144:247)
    at Object.initSearch [as init] (<anonymous>:144:508)
    at main (<anonymous>:140:176)
    at resources/skins.citizen.scripts/skin.js (<anonymous>:140:579)
```

**Comment by octfx** [comment]
Scratch this - Seems to be a stray cache entry.

But: Should there be a check around here if `checkbox` is null? https://github.com/StarCitizenTools/mediawiki-skins-Citizen/blob/9d8a631f44aac6ef97d4e2f51820c533352b5a93/resources/skins.citizen.scripts/search.js#L149

**Comment by alistair3149** [comment]
> Scratch this - Seems to be a stray cache entry.
> 
> But: Should there be a check around here if `checkbox` is null?
> 
> https://github.com/StarCitizenTools/mediawiki-skins-Citizen/blob/9d8a631f44aac6ef97d4e2f51820c533352b5a93/resources/skins.citizen.scripts/search.js#L149

I think it happened because the DOM is not fully loaded, I'm gonna delay the script from executing until it is ready, it should fix it
