### ISSUE TITLE
Thumbs appear off-centre

### ISSUE THREAD

**Issue by lachlanshanks** [StarCitizenTools/mediawiki-skins-Citizen#476]
A centred thumb appears off centre in the Citizen skin. Example: https://coasterpedia.net/wiki/Astroglide_(Coney_Beach)

The problem can be fixed by adding "overflow:hidden" to the thumb class.

**Comment by alistair3149** [comment]
Thanks for reporting it! It is fixed in 34c300d69cbd80e359b30c524e15a4f1f582eadb
