### ISSUE TITLE
Incorrect indicator for external links with the plainlinks class

### ISSUE THREAD

**Issue by ChaoticShadow** [StarCitizenTools/mediawiki-skins-Citizen#477]
## Describe the Bug
External links with the "plainlinks" class currently show the external link indicator after the link, even though it is not supposed to.

1. Go to https://projectsekai.miraheze.org/wiki/Nursing_my_ES_Gacha#Navigation
2. The "e" link in the navboxes show the indicator.
![image](https://user-images.githubusercontent.com/6554395/173208161-8a7e611b-aca5-4a04-8c2c-89eba7e4d1ca.png)

## Expected Behavior
In Vector, the links with the class "plainlinks" appear without the indicator.
![image](https://user-images.githubusercontent.com/6554395/173208205-b9953d2d-41bd-485b-8ced-59ecd0004558.png)

## System
 - MediaWiki version: 1.37.2
 - Server OS: Debian 11?
 - Installed extensions and versions: [https://projectsekai.miraheze.org/wiki/Special:Version](See here)
 - PHP version: 7.4.28

The way Vector has it handled could be modified for Citizen like
```css
.mw-parser-output .plainlinks a.external::after {
  display: none;
}
```

**Comment by alistair3149** [comment]
It is already fixed in the latest version, Miraheze haven't updated to that yet.
