### ISSUE TITLE
Bottom menu items are hard or impossible to access in mobile

### ISSUE THREAD

**Issue by lachlanshanks** [StarCitizenTools/mediawiki-skins-Citizen#481]
On a phone, the bottom item(s) in the main menu are hard or impossible to access.

On Chrome on Android there is no problem. On Firefox for Android with the menu bar at the bottom, the lowest item is only accessible if you swipe again after opening the menu to hide the address bar. On Safari on iPhone I can't hide the address bar and the lower item is inaccessible. 

The first screenshot is an iPhone XR, second one is Samsung Galaxy S9+ running Firefox.
![IMG_0010](https://user-images.githubusercontent.com/7083224/174397455-b60cf0f2-66d3-4200-806b-b7b2b4312bf2.PNG)
![Screenshot_20220617-212139_Firefox](https://user-images.githubusercontent.com/7083224/174397460-8ef3726f-ee69-40d0-9102-686ab6bc86b7.png)

**Comment by alistair3149** [comment]
Will look into it

**Comment by alistair3149** [comment]
Closing as it is no longer relevant in 2.0
