### ISSUE TITLE
Multiple jQuery errors when interacting with the VisualEditor ("A listener indicated an asynchronous response ...")

### ISSUE THREAD

**Issue by hendrikma** [StarCitizenTools/mediawiki-skins-Citizen#482]
## Describe the Bug
First of all, I would like to say a very big thank you to all the contributors! This skin is an absolute enrichment for the MediaWiki community and I am even more happy that the development is going on steadily.

I observed the following bug when interacting with the VisualEditor. When loading the VisualEditor - no matter if it is a new or already existing page - I get errors in the console.
I noticed this problem when I tried to insert hyperlinks. Clicking the button again generates about 20-30 very similar errors.

> index.php:1 Uncaught (in promise) {message: 'A listener indicated an asynchronous response by r…age channel closed before a response was received'}
> Promise.then (async)
> (anonymous) @ content_script_bundle.js:100
> handleNewFeatures @ content_script_bundle.js:93
> handleUpdatedNodes @ content_script_bundle.js:93
> (anonymous) @ content_script_bundle.js:93

> index.php:1 Uncaught (in promise) {message: 'A listener indicated an asynchronous response by r…age channel closed before a response was received'}
> Promise.then (async)
> (anonymous) @ content_script_bundle.js:100
> handleNewFeatures @ content_script_bundle.js:93
> handleUpdatedNodes @ content_script_bundle.js:93
> (anonymous) @ content_script_bundle.js:93
> attributes (async)
> addClass @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:111
> OO.ui.WindowManager.toggleGlobalEvents @ VM1045:1090
> (anonymous) @ VM1045:1084
> fire @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:46
> add @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:47
> OO.ui.WindowManager.openWindow @ VM1045:1084
> (anonymous) @ load.php?lang=de&modules=ext.visualEditor.core%2Cmwtransclusion&skin=citizen&version=180nq:709
> mightThrow @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:49
> process @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> setTimeout (async)
> (anonymous) @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> fire @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:46
> add @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:47
> (anonymous) @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:51
> Deferred @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:51
> then @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> (anonymous) @ load.php?lang=de&modules=ext.visualEditor.core%2Cmwtransclusion&skin=citizen&version=180nq:708
> fire @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:46
> add @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:47
> always @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:49
> (anonymous) @ load.php?lang=de&modules=ext.visualEditor.core%2Cmwtransclusion&skin=citizen&version=180nq:708
> mightThrow @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:49
> process @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> setTimeout (async)
> (anonymous) @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> fire @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:46
> add @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:47
> (anonymous) @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:51
> Deferred @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:51
> then @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> ve.ui.WindowAction.open @ load.php?lang=de&modules=ext.visualEditor.core%2Cmwtransclusion&skin=citizen&version=180nq:708
> ve.ui.Surface.executeWithSource @ load.php?lang=de&modules=ext.visualEditor.core%2Cmwtransclusion&skin=citizen&version=180nq:597
> ve.ui.Command.execute @ load.php?lang=de&modules=ext.visualEditor.core%2Cmwtransclusion&skin=citizen&version=180nq:625
> (anonymous) @ load.php?lang=de&modules=ext.visualEditor.core%2Cmwtransclusion&skin=citizen&version=180nq:614
> fire @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:46
> add @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:47
> ve.ui.Tool.onSelect @ load.php?lang=de&modules=ext.visualEditor.core%2Cmwtransclusion&skin=citizen&version=180nq:614
> OO.ui.ToolGroup.onMouseKeyUp @ VM1045:1123
> OO.ui.PopupToolGroup.onMouseKeyUp @ VM1045:1132
> OO.ui.ListToolGroup.onMouseKeyUp @ VM1045:1137
> OO.ui.ToolGroup.onDocumentMouseKeyUp @ VM1045:1123

> index.php:1 Uncaught (in promise) {message: 'A listener indicated an asynchronous response by r…age channel closed before a response was received'}
> Promise.then (async)
> (anonymous) @ content_script_bundle.js:100
> handleNewFeatures @ content_script_bundle.js:93
> handleUpdatedNodes @ content_script_bundle.js:93
> (anonymous) @ content_script_bundle.js:93

> index.php:1 Uncaught (in promise) {message: 'A listener indicated an asynchronous response by r…age channel closed before a response was received'}
> Promise.then (async)
> (anonymous) @ content_script_bundle.js:100
> handleNewFeatures @ content_script_bundle.js:93
> handleUpdatedNodes @ content_script_bundle.js:93
> (anonymous) @ content_script_bundle.js:93

> index.php:1 Uncaught (in promise) {message: 'A listener indicated an asynchronous response by r…age channel closed before a response was received'}
> Promise.then (async)
> (anonymous) @ content_script_bundle.js:100
> handleNewFeatures @ content_script_bundle.js:93
> handleUpdatedNodes @ content_script_bundle.js:93
> (anonymous) @ content_script_bundle.js:93
> attributes (async)
> addClass @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:111
> (anonymous) @ load.php?lang=de&modules=ext.visualEditor.core%2Cmwtransclusion&skin=citizen&version=180nq:947
> mightThrow @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:49
> process @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> setTimeout (async)
> (anonymous) @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> fire @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:46
> fireWith @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:48
> fire @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:48
> fire @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:46
> fireWith @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:48
> deferred.<computed> @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:51
> ve.dm.MWTransclusionModel.resolveChangeQueue @ load.php?lang=de&modules=ext.visualEditor.core%2Cmwtransclusion&skin=citizen&version=180nq:876
> setTimeout (async)
> ve.dm.MWTransclusionModel.processChangeQueue @ load.php?lang=de&modules=ext.visualEditor.core%2Cmwtransclusion&skin=citizen&version=180nq:877
> setTimeout (async)
> ve.dm.MWTransclusionModel.addPart @ load.php?lang=de&modules=ext.visualEditor.core%2Cmwtransclusion&skin=citizen&version=180nq:880
> (anonymous) @ load.php?lang=de&modules=ext.visualEditor.core%2Cmwtransclusion&skin=citizen&version=180nq:946
> (anonymous) @ VM1045:1078
> mightThrow @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:49
> process @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> setTimeout (async)
> (anonymous) @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> fire @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:46
> fireWith @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:48
> fire @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:48
> fire @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:46
> fireWith @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:48
> mightThrow @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> process @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> (anonymous) @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> mightThrow @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:49
> process @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> setTimeout (async)
> (anonymous) @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> fire @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:46
> add @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:47
> (anonymous) @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:51
> Deferred @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:51
> then @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> mightThrow @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> process @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> setTimeout (async)
> (anonymous) @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> fire @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:46
> fireWith @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:48
> fire @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:48
> fire @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:46
> fireWith @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:48
> mightThrow @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> process @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> (anonymous) @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> mightThrow @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:49
> process @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> setTimeout (async)
> (anonymous) @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> fire @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:46
> add @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:47
> (anonymous) @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:51
> Deferred @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:51
> then @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> mightThrow @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> process @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> setTimeout (async)
> (anonymous) @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> fire @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:46
> fireWith @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:48
> fire @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:48
> fire @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:46
> fireWith @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:48
> mightThrow @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> process @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> (anonymous) @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> mightThrow @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:49
> process @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> setTimeout (async)
> (anonymous) @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> fire @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:46
> add @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:47
> (anonymous) @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:51
> Deferred @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:51
> then @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> mightThrow @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> process @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> setTimeout (async)
> (anonymous) @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> fire @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:46
> add @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:47
> (anonymous) @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:51
> Deferred @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:51
> then @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> OO.ui.Process.execute @ VM1045:1078
> OO.ui.Window.setup @ VM1045:1097
> (anonymous) @ VM1045:1085
> setTimeout (async)
> (anonymous) @ VM1045:1085
> fire @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:46
> add @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:47
> OO.ui.WindowManager.openWindow @ VM1045:1084
> (anonymous) @ load.php?lang=de&modules=ext.visualEditor.core%2Cmwtransclusion&skin=citizen&version=180nq:709
> mightThrow @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:49
> process @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> setTimeout (async)
> (anonymous) @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> fire @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:46
> add @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:47
> (anonymous) @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:51
> Deferred @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:51
> then @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> (anonymous) @ load.php?lang=de&modules=ext.visualEditor.core%2Cmwtransclusion&skin=citizen&version=180nq:708
> fire @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:46
> add @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:47
> always @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:49
> (anonymous) @ load.php?lang=de&modules=ext.visualEditor.core%2Cmwtransclusion&skin=citizen&version=180nq:708
> mightThrow @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:49
> process @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> setTimeout (async)
> (anonymous) @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> fire @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:46
> add @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:47
> (anonymous) @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:51
> Deferred @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:51
> then @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:50
> ve.ui.WindowAction.open @ load.php?lang=de&modules=ext.visualEditor.core%2Cmwtransclusion&skin=citizen&version=180nq:708
> ve.ui.Surface.executeWithSource @ load.php?lang=de&modules=ext.visualEditor.core%2Cmwtransclusion&skin=citizen&version=180nq:597
> ve.ui.Command.execute @ load.php?lang=de&modules=ext.visualEditor.core%2Cmwtransclusion&skin=citizen&version=180nq:625
> (anonymous) @ load.php?lang=de&modules=ext.visualEditor.core%2Cmwtransclusion&skin=citizen&version=180nq:614
> fire @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:46
> add @ load.php?lang=de&modules=jquery&skin=citizen&version=11a6j:47
> ve.ui.Tool.onSelect @ load.php?lang=de&modules=ext.visualEditor.core%2Cmwtransclusion&skin=citizen&version=180nq:614
> OO.ui.ToolGroup.onMouseKeyUp @ VM1045:1123
> OO.ui.PopupToolGroup.onMouseKeyUp @ VM1045:1132
> OO.ui.ListToolGroup.onMouseKeyUp @ VM1045:1137
> OO.ui.ToolGroup.onDocumentMouseKeyUp @ VM1045:1123

![mediawiki-citizen-jquery-error](https://user-images.githubusercontent.com/53167459/174673088-f6d79a99-6bb9-466c-9c66-a565b507be8a.PNG)

An so on ...

1. Go to Edit/Create with the VisualEditor
2. Click on "Add Link"
3. See error in Console

## Expected Behavior
I expected a modal to open up.

## System
_Please complete the following information:_
 - MediaWiki version 1.37.2
 - Server OS: Official Docker Image from mediawiki:latest

I would be very happy if this bug could be fixed in the future and hope to have contributed something to improve the great skin ;)

**Comment by alistair3149** [comment]
Closed since it is not related to Citizen
