### ISSUE TITLE
Add Style Support for AJAXPoll

### ISSUE THREAD

**Issue by AlanYe-Dev** [StarCitizenTools/mediawiki-skins-Citizen#487]
The default style of AJAXPoll looks outdated. In 2017 someone requested to convert this extension to OOUI on Phabricator, but there were no more reply since 2018.

My Citizen skin version is 1.17.7 (currently up to date), and the screenshots are as follows.

![Screenshot_20220710-002243.png](https://user-images.githubusercontent.com/45558679/178114334-6938bc17-8d11-4831-86c5-92b99443c134.png)
![Screenshot_20220710-002248.png](https://user-images.githubusercontent.com/45558679/178114341-9dafb530-23e0-4a16-9827-ce6e309c6058.png)

(It's awful, isn't it?)

**Comment by alistair3149** [comment]
Style added in the latest version. Closing the issue
