### ISSUE TITLE
Some buttons in VisualEditor dialogue don't go dark in dark mode

### ISSUE THREAD

**Issue by lachlanshanks** [StarCitizenTools/mediawiki-skins-Citizen#489]
In dark mode when editing a template in VisualEditor with the complex TemplateData set, the "More" button appears light when it should be dark.

Try editing the infobox template on this article: https://coasterpedia.net/wiki/Arkham_Asylum_-_Shock_Therapy

**Comment by alistair3149** [comment]
Fixed in the latest verison.
