### ISSUE TITLE
Highlighted Search Suggestions Collapse Spaces in Partial Title

### ISSUE THREAD

**Issue by BobtheGreatII** [StarCitizenTools/mediawiki-skins-Citizen#494]
## Describe the Bug
When using the search bar to find a page, the search suggestion highlight seems to remove the space between the highlight span and regular text if the search includes a full word from the title. 

1. Go to Search
2. Type a partial search that includes a full word from an article title.
3. Notice how the space between the highlighted word and the rest of the title is gone.

I'm able to replicate this on the [starcitizen.tools](https://starcitizen.tools/) wiki as well.

## Expected Behavior
I would expect that the space between the highlighted word and the rest of the title would be maintained.

## Temp Fix
I was able to work around this by adding `display:block` to the `.citizen-typeahead-suggestion__title` and `.citizen-typeahead-suggestion__description` classes in CSS.
 
Before:
![Screenshot 2022-07-27 092810](https://user-images.githubusercontent.com/46304655/181288973-b19949aa-28c1-4584-a4ae-e56b592369b7.png)
Temp Fix:
![Screenshot 2022-07-27 092743](https://user-images.githubusercontent.com/46304655/181288970-ae10cc1c-abe2-4df5-a825-5a147b896945.png)
After:
![Screenshot 2022-07-27 093255](https://user-images.githubusercontent.com/46304655/181288964-5a7d5657-4894-4a34-88a4-30e86432b1e6.png)

## System
 - MediaWiki version 1.37.1
 - Server OS: Windows Server 2012 R2
 - PHP version 7.4.29

**Comment by alistair3149** [comment]
Thanks for the report! I can reproduce the issue and am looking into it.
