### ISSUE TITLE
Changing theme color isn't working

### ISSUE THREAD

**Issue by Ne14k** [StarCitizenTools/mediawiki-skins-Citizen#498]
## Describe the Bug
I changed the theme color of the skin on mobilefrontend to match the background of darkvector with the hexcode "#333232". So I added this to the localsettings.php file: $wgCitizenThemeColor = '#333232';
It did absolutley nothing, even thought this is how it's usage is stated in the configuration.
Desktop View: https://lain.wiki/index.php?title=Main_Page&mobileaction=toggle_view_desktop
Mobile View: https://lain.wiki/index.php?title=Main_Page&mobileaction=toggle_view_mobile
Here is a picture of the desktop view:
![image](https://user-images.githubusercontent.com/95349960/183020146-abe060df-42b8-4a3e-bd7e-ddfbdcfaef33.png)
Here is a picture of the mobile view (Some parts are colored grey and red because they were colored like that from wikipedia page and not from the actual skin):
![Screenshot 2022-08-05 030207](https://user-images.githubusercontent.com/95349960/183021067-1a58d56a-4a62-419d-a1d3-d9f1ad51f582.png)

1. Install Citizen Skin
2. Add this to your localsettings.php: $wgCitizenThemeColor = '#333232';
3. Relaunch your site
5. Doesn't change the theme color, same light and dark mode.

## Expected Behavior
I expected the theme/background color to switch to #333232 but, it just stayed the same. Even switching between, light, auto and dark mode doesn't do anything (default is dark mode).

## System
_Please complete the following information:_
 - MediaWiki version [e.g. v1.35.4]
 - Server OS: [e.g. Ubuntu 22.04 LTS Server]
 - Installed extensions and versions [Citizen 1.17.8, DarkVector, Vector, MonoBook, Timeless 0.8.9, Nuke 1.3.0, CodeMirror 4.0.0, WikiEditor 0.5.3, Babel 1.12.0, Cite, ImageMap, InputBox 0.3.0, ParserFunctions 1.6.0, Poem, SyntaxHighlight 2.0, WikiSEO 2.6.5, ConfirmEdit 1.6.0, QuestyCaptcha, SpamBlacklist, CLDR, Clean Changes, Gadgets MobileFrontend 2.3.0, Theme 1.7.2]
 - PHP version [7.4.30 (fpm-fcgi)]

**Comment by octfx** [comment]
The documentation may be a little misleading, `$wgCitizenThemeColor` is only used for setting the `theme-color` meta tag.

To change the color of your background you'd need to set either in `MediaWiki:Common.css` or `MediaWiki:Citizen.css`.

**Comment by Ne14k** [comment]
What would you add to `MediaWiki:Citizen.css` to make the background-color: #333232?
Also, do you have instagram or discord. I feel like it's easier to communicate through those apps then in a github thread.

**Comment by octfx** [comment]
The [MediaWiki Discord](https://discord.gg/ZrV2Ex9) usually helps with any questions regarding MediaWiki and its extensions / skins.

You can have a look over [here](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/wiki/Customizing-Citizen-styles) and [here](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/wiki/Adapting-Citizen-styles) to get started with customizing the skin.

You'd need to add the following code to `MediaWiki:Citizen.css` in order to change the background color:
```css
:root {
  --color-surface-0: #333232;
}

:root.skin-citizen-dark {
  --color-surface-0: #333232;
}
```
The first rule targets the light version of the skin, that second sets the color in dark mode.

**Comment by Ne14k** [comment]
It's working for the desktop view of the citizen skin
![image](https://user-images.githubusercontent.com/95349960/183042166-5f97d919-9543-4d3b-a55c-8fc7478fd64a.png)
but the mobilefrontend using the citizen skin is still the same
![image](https://user-images.githubusercontent.com/95349960/183042266-ca987a6b-dd7a-4319-ab63-8958bd9dafb7.png)

**Comment by Ne14k** [comment]
Hey sorry to bother you, but I cannot find the  class or id for this one button, I'm trying to change it orange.
![image](https://user-images.githubusercontent.com/95349960/183225889-c56753df-b4c7-40c7-9180-4d598254f1ff.png)
This is what I intend it to look like
![image](https://user-images.githubusercontent.com/95349960/183225946-9337d82c-8d26-4a3e-b264-15ac3c56951d.png)
Also, I tried the MediaWiki discord but, it's very inactive.

**Comment by alistair3149** [comment]
Footer is redesigned in the 2.X version and it will change color based on the theme selected.
It seems that the above issues are all resolved, closing the issue now.
Thanks @octfx for the help!
