### ISSUE TITLE
Zooms in when editing text on iOS devices

### ISSUE THREAD

**Issue by lachlanshanks** [StarCitizenTools/mediawiki-skins-Citizen#513]
When editing using an iPhone (I have the XR) the page zooms in when trying to edit text. From memory this can be fixed by increasing the font size to 17px but also seems like it can be[ fixed using the viewport tag](https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone). Unfortunately I haven't managed to test this because from looking at the Citizen code it seems MediaWiki sets the "maximum-scale" figure already and I don't know how to edit that.

The problem is present on both Coasterpedia and the Star Citizen wiki.

**Comment by alistair3149** [comment]
The viewport tag is added by MW core using the responsive flag. It seems that it is the intended behavior on their end but I will look into it.

**Comment by lachlanshanks** [comment]
Thanks, I took a look at Wikipedia and MobileFrontend there doesn't do it, so maybe there is something you can add from MobileFrontend?

**Comment by alistair3149** [comment]
> Thanks, I took a look at Wikipedia and MobileFrontend there doesn't do it, so maybe there is something you can add from MobileFrontend?

I'm not sure about Minerva with MobileFrontend but Vector doesn't have the responsive flag enabled. I can skip the MW implementation and manually add the tag, but I need to look more into it
