### ISSUE TITLE
Double Search Suggestion Boxes on Search Results Page

### ISSUE THREAD

**Issue by BobtheGreatII** [StarCitizenTools/mediawiki-skins-Citizen#520]
If you attempt another search while on a search results page, you are shown the old style search suggestions on top of the formatted search suggestions for the Citizen skin.

1. Search for anything on the wiki.
2. Once on a search results page, attempt another search.

![doublesearchresults](https://user-images.githubusercontent.com/46304655/192880910-543c02fc-d750-45ac-aea8-6e6dba34a80b.png)

I am able to replicate this on both my wiki and the [Star Citizen Wiki](https://starcitizen.tools/).

Thank you!

**Comment by alistair3149** [comment]
Should be fixed in the latest version
