### ISSUE TITLE
When adding a source/reference in dark mode, the text is white on a white background

### ISSUE THREAD

**Issue by forteller** [StarCitizenTools/mediawiki-skins-Citizen#525]
## Describe the Bug

1. Go to edit any page
2. Click on Add source or Add reference (I'm using the skin in Norwegian, so I'm not totally sure what it says in English, but something like that. It's right next to the link button)
3. Start typing in the white box, notice that you can't see whatever you've typed

![image](https://user-images.githubusercontent.com/343561/193451091-53ee8571-f407-4bf2-a2de-ef54476e82f6.png)

Select all:
![image](https://user-images.githubusercontent.com/343561/193451105-57f29500-3c1f-4dde-bb11-1f9e005268f3.png)

## Expected Behavior
The text should be visible.

## System
Sorry, I'm not sure about the technical info. I'm on Miraheze, so I'm using whatever they're using. If you need any extra info, please let me know and I'll find out.

Thank you so much!

**Comment by alistair3149** [comment]
Fixed in the latest verison.
