### ISSUE TITLE
Text of anchors is behind the header

### ISSUE THREAD

**Issue by williamsp** [StarCitizenTools/mediawiki-skins-Citizen#533]
## Describe the Bug
Text of anchors is behind the header.

1. Go to Reference section
2. Click on any number to open the cite ref
3. The text that using the ref is not visible on screen, it is behind the header

or

1. Click on any link on the Contents sidebar
2. The section title is not visible on screen, it is behind the header

## Expected Behavior
Text of anchors is visible, should be below the header

## System
Producable on https://starcitizen.tools

**Comment by alistair3149** [comment]
Thanks for the report! It should now be fixed :)
