### ISSUE TITLE
Deprecated skin method (1.38)

### ISSUE THREAD

**Issue by felipeforte** [StarCitizenTools/mediawiki-skins-Citizen#541]
The newer MediaWiki stable version (1.38.4) has deprecated a few Skin methods. 

Full error log:

`Deprecated: Use of SkinTemplate::buildContentNavigationUrls was deprecated in MediaWiki 1.38. [Called from SkinCitizen::buildContentNavigationUrlsPublic in /mediawiki/skins/Citizen/includes/SkinCitizen.php at line 159] in /mediawiki/includes/debug/MWDebug.php on line 377`

**Comment by alistair3149** [comment]
Thanks for the report!
It is a soft deprecation that shouldn't affect anything functionality-wise on 1.38. The method is already deprecated in the 1.39 branch of the skin.
