### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by RemainingToast** [StarCitizenTools/mediawiki-skins-Citizen#543]
## Describe the Bug
Fatal error: Cannot override final method Skin::getPortletData() in /var/www/html/w/skins/Citizen/includes/SkinCitizen.php on line 220

**Comment by alistair3149** [comment]
MediaWIki 1.39 changed getPortletData to final.
You can use the current [development branch for 1.39](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/tree/citizen_2.0) if you are on 1.39. Note that it is not stable yet and subject to change until 1.39 officially release.
