### ISSUE TITLE
Fatal error: Cannot override final method Skin::getPortletData() 

### ISSUE THREAD

**Issue by jdlrobson** [StarCitizenTools/mediawiki-skins-Citizen#546]
## Describe the Bug
in /vagrant/mediawiki/skins/Citizen/includes/SkinCitizen.php on line 220

1. Use 1.40 of MediaWiki
2. Load any page.

## Expected Behavior
We made this a final method in preparation for moving away from it. I believe you can work around this for now, by added a method getPortletDataNotFinal and call getPortlet but long term this function will not be available in favor of a component system we've been moving towards.

Let me know if I can help!

**Comment by alistair3149** [comment]
Thanks for taking the time to open an issue!

This has been resolved in the current `Citizen_2.0` branch, along with thousands of technical debt accumulated since 1.35. 
It is just not merged into `main` yet because MW 1.39 stable has not been released. I will merge the branch when 1.39 drops.
