### ISSUE TITLE
Table Of Contents and Page Content Overlapping On Scroll

### ISSUE THREAD

**Issue by iAdam1n** [StarCitizenTools/mediawiki-skins-Citizen#551]
As the video shows, if you scroll so far, the table of content and page content overlaps. I'd suggest maybe either automatically close the TOC if scrolled text is going to overlap it or make it so that the scroll does not go as far as the TOC. 

https://user-images.githubusercontent.com/2139641/203196345-7fb637d4-781b-4542-92fb-eeef9bad1828.mov

**Comment by alistair3149** [comment]
Closing as it is fixed in 2.0, 1.X are no longer being developed.
