### ISSUE TITLE
Skin does not load.

### ISSUE THREAD

**Issue by N0W0RK** [StarCitizenTools/mediawiki-skins-Citizen#552]
On MediaWiki version 1.39.0-rc.0
and skin Version 2.0.0 the wiki si displayed as if no CSS was loaded.
Skin version beta4 does however work.
Its a fairly fresh install.

**Comment by alistair3149** [comment]
Do you have a live site that I can look into?
And do you have any error message on the browser console or the loaded stylesheets?

**Comment by N0W0RK** [comment]
Sure, you can have a look at wiki.tuti.lol . Currently in the process of building it up so there might be some changes.

**Comment by N0W0RK** [comment]
If you want, I can upgrade the skin again to the full release.

**Comment by alistair3149** [comment]
I can't reproduce it on my side, would you mind to do the following on the latest version of the skin?

1. Right click and click `Inspect` to open the dev tools
2. Go to the `Network` tab
3. Reload the page
4. Click on the first stylesheet that get loaded
5. Click the `preview` tab
6. Check if there is any error message there

**Comment by N0W0RK** [comment]
I have no `preview` Tab that I can see on Firefox.
However this is ontop of the css:
```
/*
[a8b0bd583b9e8213de1b4f85] 2022-11-22 16:41:22: Fatal exception of type "Less_Exception_Parser"

Problematic modules: {"skins.citizen.styles":"error"}
*/
```

**Comment by alistair3149** [comment]
Try doing a clean install of the skin by removing all the files and download it again. See if you can reproduce the same error

**Comment by N0W0RK** [comment]
Thats what i did. 
Downloaded `main.zip` and extracted it. Moved the contents into `Citizen`.
My LocalSettings.php remained the same.

**Comment by N0W0RK** [comment]
Works perfectly thank you
