### ISSUE TITLE
[REL1_35] Missing `skins.citizen.scripts.drawer.js`

### ISSUE THREAD

**Issue by octfx** [StarCitizenTools/mediawiki-skins-Citizen#554]
Using the REL1_35 branch, I am seeing the following error:
```
/ResourceLoaderFileModule.php: ResourceLoaderFileModule::getFileContents: script file not found, or is not a file: "/var/www/html/skins/Citizen/resources/skins.citizen.scripts.drawer/skins.citizen.scripts.drawer.js"
```

Indeed looking at `skin.json` https://github.com/StarCitizenTools/mediawiki-skins-Citizen/blob/6a57ccc1928749c346cef161cdf25841fd3fd616/skin.json#L214 this file is referenced, but the `resources` folder does not contain such a file.

**Comment by alistair3149** [comment]
It should be fixed now. It was some leftover references from before.
