### ISSUE TITLE
Remove Footer tab

### ISSUE THREAD

**Issue by cranioisthinking** [StarCitizenTools/mediawiki-skins-Citizen#557]
Hi, how can I remove footer tab from the page?
Thanks in advance

**Comment by alistair3149** [comment]
What do you mean by footer tab?

**Comment by cranioisthinking** [comment]
Hi, and thanks for your reply, 
I mean this:

![image](https://user-images.githubusercontent.com/44480417/208319126-2d8c4840-aa2c-4158-9d67-c8fd69e298ce.png)


thanks in advance

**Comment by alistair3149** [comment]
Do you mean the whole footer or just the tagline?
If it is the whole footer, it is a default MediaWiki feature and you can hide it through CSS.

**Comment by cranioisthinking** [comment]
Thanks. 
Can you help me to find the right file where to remove the css of footer?

**Comment by alistair3149** [comment]
You can just do it through `MediaWiki:Citizen.css` on your wiki.
