### ISSUE TITLE
PdfHandler navigation overlaps pdf image

### ISSUE THREAD

**Issue by octfx** [StarCitizenTools/mediawiki-skins-Citizen#56]
The navigation to change pdf pages overlaps the rendered pdf page.

1. Open any pdf filepage with Extension:PdfHandler enabled

## Expected Behavior
![895-551-max](https://user-images.githubusercontent.com/6594492/71780438-951ba800-2fc2-11ea-96f1-f8406295d86c.png)

## Actual Behavior
![887-665-max](https://user-images.githubusercontent.com/6594492/71780442-a6fd4b00-2fc2-11ea-9253-a9323e889cd5.png)

**Comment by alistair3149** [comment]
Do you have a link to the page with the issue? I will look into it.

**Comment by octfx** [comment]
> Do you have a link to the page with the issue? I will look into it.

Sure! https://star-citizen.wiki/Datei:CRSD_Hercules_Serie_Brosch%C3%BCre.pdf?useskin=citizen

**Comment by alistair3149** [comment]
Would you mind to check if b853dd3 fixed the issue for you?

**Comment by octfx** [comment]
This fixes the issue! 😄 

To add to this, I'd propose to add something like:
```css
table.multipageimage td {
    display: block;
}

table.multipageimage td:last-of-type {
    margin-top: 0.8rem;
}
```
Which would result in: 
![907-993-max](https://user-images.githubusercontent.com/6594492/71911468-077fba00-3174-11ea-997a-4f715fdccae5.png)

However I haven't checked if this changes the layout of other pages.

**Comment by alistair3149** [comment]
Okay I added those changes and they will be merged to dev then master
