### ISSUE TITLE
Cargo Dynamic Tables with 2 or more Hidden Fields break styling

### ISSUE THREAD

**Issue by Tarquinous** [StarCitizenTools/mediawiki-skins-Citizen#571]
## Describe the Bug
When building tables using Cargo with a Dynamic Table format, have multiple on the same page, under certain conditions only the first table will render correctly. All other tables will break, and no table's expandable "Detail fields" will work. The conditions are:
* There is at least 2 tables on the page.
* At least 2 tables have a Details Field set.
* At least 1 table has a total 15 columns _not_ in Details Field **and** has at least 2 of those columns set as Hidden Fields

## Expected Behavior

You can find an example of this behaviour at: https://www.dustloop.com/w/User:Emo_Tarquin/CargoDemo

Below is a screenshot showing part of this:
![cargoBrokenExample](https://user-images.githubusercontent.com/77987607/212501178-a99aec84-fe91-4f92-987b-01e944754d1c.JPG)

Note the two tables are different, the upper table has expected and functioning display properties, the lower table has lost styling attributes and no longer displays correctly. Normally the green + buttons allow the row to expand to show information in the Details Fields, but in this case the buttons will not interact and do anything.

This issue may be related to Cargo behaviour and not tied to the skin, especially given Cargo's instability in the past. But I felt it was worth reporting in case this can be addressed.

**Comment by alistair3149** [comment]
It is an upstream issue on Cargo side.
```
jQuery.Deferred exception: Cannot read properties of undefined (reading 'bVisible') 
TypeError: Cannot read properties of undefined (reading 'bVisible')
```
![image](https://user-images.githubusercontent.com/9260542/212501927-bb9a03e8-016e-492c-974e-13e85d431d4f.png)
