### ISSUE TITLE
Map overlaying menus

### ISSUE THREAD

**Issue by RothwellWiki** [StarCitizenTools/mediawiki-skins-Citizen#577]
## Describe the Bug
Maps on my wiki overlay menus, such as the toggle menu, preferences, notifications, more actions and search.

1. Go to 'https://www.rothwell-leeds.co.uk/wiki/Main_Page?useskin=citizen' or 'https://www.rothwell-leeds.co.uk/wiki/Template:Main_Map?useskin=citizen'
2. Click on any menu, but it's most easily seen with either the search or the toggle menu.
3. Scroll so that the menu and map overlap.
4. See error.

## Expected Behavior
I would expect the menus to overlay the maps.

## System
 - MediaWiki version: 1.39.1 (03f84a5)
 - Installed extensions and versions: Citizen 2.3.5 (b1a2604) and Extension:Maps 10.0.0 (b889fd0)
 - PHP version: 7.4.30 (fpm-fcgi)
 - Wiki Farm: Miraheze

## Images

![Screenshot 2023-02-03 at 14 17 09](https://user-images.githubusercontent.com/109766234/216626000-8449c3bc-6ac4-4699-a5f2-10a9104327a7.png)
![Screenshot 2023-02-03 at 14 17 21](https://user-images.githubusercontent.com/109766234/216626015-e29f08b7-75fa-4ac0-8e3d-e76bb2efe859.png)
![Screenshot 2023-02-03 at 14 17 30](https://user-images.githubusercontent.com/109766234/216626021-b6177403-c923-49ed-a634-54bf6893d02e.png)
![Screenshot 2023-02-03 at 14 17 41](https://user-images.githubusercontent.com/109766234/216626026-21d8c6cc-5762-40e6-a088-1f7c4a67bc5d.png)
![Screenshot 2023-02-03 at 14 20 43](https://user-images.githubusercontent.com/109766234/216626645-d61456ae-9225-4386-bc66-064073222f39.png)

**Comment by alistair3149** [comment]
It is caused by the high z-index from the Maps extension.
I looked into the source code and it is using another library. I am not comfortable at altering it, as I am not sure about its use cases, so I will put this on hold for now.

In the meantime, you can use the below CSS to fix it:
```css
.maps-leaflet {
    z-index: 0;
}
```

**Comment by RothwellWiki** [comment]
Thanks alistair3149. The CSS seemed to fix it on desktop, but did not make any affect on mobile. Do you have any idea how I could fix this?

**Comment by alistair3149** [comment]
Looks like you're using MobileFrontend. In that case, you also need to put it in MediaWiki:Mobile.css.

**Comment by RothwellWiki** [comment]
For some reason, that didn't work. However, I found that adding the CSS using TemplateStyles to pages with maps fixed it.
Thanks for your help!

**Comment by alistair3149** [comment]
Would you be able to test if the latest commit fix it for you? I have added custom styles for Leaflet and it should help too.
