### ISSUE TITLE
Click User Edit Count to view their contributions 

### ISSUE THREAD

**Issue by sirjamesgray** [StarCitizenTools/mediawiki-skins-Citizen#578]
The below image explains visually what I'm talking about. This text should be a link to the User's contribution page. That would reduce the number of clicks necessary to get to the user's contribution page. 
![image](https://user-images.githubusercontent.com/16139439/216750786-74b9afdf-f06e-43e1-ad5b-4d1b702b205c.png)

**Comment by alistair3149** [comment]
That is a great idea! I will look into it soon!

**Comment by sirjamesgray** [comment]
any updates on this? @alistair3149

**Comment by Dringsim** [comment]
> any updates on this? @alistair3149

added in #657

**Comment by alistair3149** [comment]
Oops forgot to include the close message in the commit, my bad. This is now resolved.
