### ISSUE TITLE
Additions after 'navigation' missing in Sidebar

### ISSUE THREAD

**Issue by Reception123** [StarCitizenTools/mediawiki-skins-Citizen#580]
## Describe the Bug
Only the items in the navigation section are included, further custom sections don't appear in the sidebar since 1.39.

1. Open the wiki, and open the menu containing wiki links (3 lines)
2. Notice none of the custom additions in MediaWiki:Sidebar are included for one reason or another.

## Expected Behavior
Both the navigation and the custom pages section should be in the sidebar

## System

MediaWiki | **1.39.1** (1c58291)
PHP | 7.4.33 (fpm-fcgi)
MariaDB | 10.5.17-MariaDB-1:10.5.17+maria~deb11-log

Original task and wiki: https://phabricator.miraheze.org/T10450

**Comment by alistair3149** [comment]
It seems to be a duplicate of https://phabricator.miraheze.org/T10334.

The issue can be reproduced when the user has ManageWiki access, in which the user can only get the first portlet of the sidebar. I suspect that there are some incompatibility between how ManageWiki and Citizen handle sidebar, but I'm not sure the exact cause even after looking into the source.

**Comment by Reception123** [comment]
Oh you're right, when logged out it works fine.

**Comment by williamsp** [comment]
Hi, could someone check what's wrong with nucarnival.miraheze.org? Here, logged out users also cannot see additional sections on the sidebar.

Details here: https://phabricator.miraheze.org/T10334#209346
