### ISSUE TITLE
LanguageConverter does not function in Table of Contents

### ISSUE THREAD

**Issue by LuciferianThomas** [StarCitizenTools/mediawiki-skins-Citizen#581]
## Describe the Bug
[LanguageConverter](https://www.mediawiki.org/wiki/Writing_systems/LanguageConverter) does not function on the Table of Contents in the Citizen skin for wikis in Chinese and possibly various other languages with LanguageConverter implemented in MediaWiki. This exact same issue happened with the Vector 2022 skin, so the method of fixing would likely be similar, please refer to [Wikimedia Phabricator task T306862](https://phabricator.wikimedia.org/T306862) for details.

1. Go to any content page on the Chinese Star Citizen wiki with a ToC with user language as any Chinese variant (`zh-hant` `zh-hans` `zh-tw` `zh-hk` `zh-mo` `zh-cn` `zh-my` `zh-sg`) ([example in zh-hk](https://citizenwiki.cn/wiki/%E9%A3%9E%E8%88%B9%E7%BB%84%E4%BB%B6?uselang=zh-hk))
2.  The ToC is not converted to the target variant, and remains in the variant used in the wikitext.

## Expected Behavior
The Chinese characters in the sidebar table of the contents should be converted to match the converted ones in pages, e.g. in example page with `uselang=zh-hk` the first content title should be `組建類型` (converted to `zh-hk`) instead of `组建类型` as in raw wikitext.

## System
_Please complete the following information:_
 - MediaWiki version: v1.39.1
 - Server OS: whichever Miraheze uses (I think Linux), but shouldn't matter
 - Installed extensions and versions: see [Special:Version for Chinese Star Citizen wiki](https://citizenwiki.cn/wiki/Special:%E7%89%88%E6%9C%AC), but also shouldn't matter
 - PHP version: 7.4.30 (fpm-fcgi)

**Comment by alistair3149** [comment]
As you can see, it is an upstream issue on the MediaWiki core parser where the language variant conversion isn't being applied to the Table of Content. I am more inclined to wait for the core fix since I am not familiar with that part of the parser, and it affects all skins that uses the mustache data to render ToC.

**Comment by alistair3149** [comment]
Fixed upstream in MediaWiki core
