### ISSUE TITLE
No language change possible with Language Extension Bundle

### ISSUE THREAD

**Issue by ManuelHaas** [StarCitizenTools/mediawiki-skins-Citizen#587]
## Describe the Bug
Using current citizen skin (2.40), there is no possibility to switch language for a wiki that provides mulitple languages via translate extension. You can neither change the interface language nor the language of the displayed content. Functionality is working fine with timeless skin.

1. Is language support only provided if using InterWiki extension because this is not installed?
2. Or is there any config setting necessary to get a language selector button like in the german citizen wiki?

## Expected Behavior
Language selection button to switch between the provided wiki languages.

## System
 - MediaWiki version v1.39.1
 - Server OS: Ubuntu 22.04.1
 - Installed extensions and versions: Language Extension Bundle 2023-01-24 [MLEB 2023.01](https://www.mediawiki.org/wiki/MLEB)
 - PHP version 8.0.27

**Comment by alistair3149** [comment]
Will look into it

**Comment by alistair3149** [comment]
So to answer your question, the language selection button only appears for any extension that modifies the languages sidebar menu by default, that includes Extension:Interwiki.

To apply this behavior for Extension:Translate, you need to put the following config in `localsettings.php`
```php
$wgPageTranslationLanguageList = 'sidebar-only';
```

On a side note, Extension:Interwiki and Extension:Translate treat languages differently. Extension:Interwiki links independent wikis for languages (e.g. English Wikipedia and German Wikipedia are separate wikis, linked through Interwiki). While Extension:Translate links pages on the same wiki (e.g. Article/en for English and Article/de for German on the same wiki).

**Comment by ManuelHaas** [comment]
Thank you very much for the detailed explanation!
So far it works well with this setting set.
