### ISSUE TITLE
wgLanguageCode setting seems to be ignored

### ISSUE THREAD

**Issue by ManuelHaas** [StarCitizenTools/mediawiki-skins-Citizen#588]
## Describe the Bug
Using current citizen skin (2.40) The UI language is english even if `$wgLanguageCode = "de";` is set.

## Expected Behavior
UI language should be set according to `wgLanguageCode` setting. Is there a different setting used?

## System
 - MediaWiki version v1.39.1
 - Server OS: Ubuntu 22.04.1
 - Installed extensions and versions: Language Extension Bundle 2023-01-24 [MLEB 2023.01](https://www.mediawiki.org/wiki/MLEB)
 - PHP version 8.0.27

**Comment by alistair3149** [comment]
Not a bug related to Citizen, see #589 for explanation.
