### ISSUE TITLE
UI language is not updated to selected translation language

### ISSUE THREAD

**Issue by ManuelHaas** [StarCitizenTools/mediawiki-skins-Citizen#589]
## Describe the Bug
Using current citizen skin (2.40) if I switch language using the dropdown provided by the setting `$wgPageTranslationLanguageList = 'sidebar-only';` the UI language is not changed.

## Expected Behavior
The UI language changes to the language that is selected in the translation language dropdown. I think this is one of the known bugs that alistair3149 mentioned.

## System
 - MediaWiki version v1.39.1
 - Server OS: Ubuntu 22.04.1
 - Installed extensions and versions: Language Extension Bundle 2023-01-24 [MLEB 2023.01](https://www.mediawiki.org/wiki/MLEB)
 - PHP version 8.0.27

**Comment by alistair3149** [comment]
It is not a bug of Citizen itself, it is [how MediaWiki structure langauges](https://www.mediawiki.org/wiki/Manual:Language).

**Site content language** is set by `$wgLanguageCode`.
**User interface language** is set by user preference or through Extension:UniversalLanguageSelector.
**Page content language** can be set by Extension:Translate if it is different than the site content.

You can try the following config to see if it helps, it has been a while since I worked with MLEB extensions:
```php
# If set to true, when a user selects an interface language via ULS (Universal Language Selector), if the current page is a translatable page or a translation page then the user is also redirected to the corresponding translation page in the selected language.
# The language of the translation pages visited afterwards will still depend on the links followed (it will be the interface language only if the links use the Special:MyLanguage syntax).
$wgTranslatePageTranslationULS = true;
```

**Comment by ManuelHaas** [comment]
@alistair3149 Thanks for immediate response!
`$wgTranslatePageTranslationULS = true;` is already set and it works fine with timeless skin.
Any hints what can be the problem then?

**Comment by alistair3149** [comment]
Do you have an example page that I can look into?

**Comment by ManuelHaas** [comment]
https://userguide.hitguard.de/index.php/Hauptseite

**Comment by alistair3149** [comment]
On the Timeless skin, did you switch language through this menu?

![image](https://user-images.githubusercontent.com/9260542/219467429-ecc97252-7ff2-4e6a-b824-e714c2e0cc6e.png)

That button is the button for Universal Language Selector, Citizen also has the same menu under the user menu.

**Comment by ManuelHaas** [comment]
Yes, exactly with this button.
Where is this button in citizen?
![image](https://user-images.githubusercontent.com/10881695/219467873-2c66e092-8b88-4771-8136-037aafeb1152.png)

**Comment by ManuelHaas** [comment]
@alistair3149 Language switching works wonderfully with 2.4.1 via the user button. 
Stupid question: How do I get this language button that is hidden under user instead of the translate language list button to the top right?

**Comment by alistair3149** [comment]
There isn't a good way unfortunately, I have been exploring other ways to tackle it but no promises so far.
