### ISSUE TITLE
font-style and font-variant properties don't apply

### ISSUE THREAD

**Issue by ChaoticShadow** [StarCitizenTools/mediawiki-skins-Citizen#591]
## Describe the Bug
The CSS properties "font-style" and "font-variant" have no effect.

1. Visit any page with this styling (Main Page for "front-style" and almost any page has italics for "font-variant")
1. See error

## Expected Behavior
Small caps
![image](https://user-images.githubusercontent.com/6554395/219547282-3148ad3b-345e-4808-995e-32e71fb0c08a.png)

Italics
![image](https://user-images.githubusercontent.com/6554395/219547363-9df720ac-5f77-4b28-8351-05363caf1030.png)

I checked Star Citizen wiki for reference and italics and small caps appear to be working on Citizen 2.3.6.

## System
 - MediaWiki version: 1.39.1 (bcc4970)
 - Server OS: Unknown (possibly still Debian 11)
 - Installed extensions and versions: [See here](https://www.sekaipedia.org/wiki/Special:Version)
 - PHP version 7.4.33 (fpm-fcgi)
 - Citizen version: 2.4.1

**Comment by alistair3149** [comment]
Should be fixed now, it seems that the synthesis rule need some more work.
