### ISSUE TITLE
Parent page is not shown when on a subpage

### ISSUE THREAD

**Issue by WerySkok** [StarCitizenTools/mediawiki-skins-Citizen#592]
## Describe the Bug
When I'm on my wiki on [Nemo's Transit Expansion/Добавление полигональных моделей](https://mtrwiki.murs-mc.ru/wiki/Nemo%27s_Transit_Expansion/%D0%94%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_%D0%BF%D0%BE%D0%BB%D0%B8%D0%B3%D0%BE%D0%BD%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D1%85_%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D0%B5%D0%B9) on page that is a subpage of [Nemo's Transit Expansion](https://mtrwiki.murs-mc.ru/wiki/Nemo%27s_Transit_Expansion) I can't find any links to go upper.

![изображение](https://user-images.githubusercontent.com/15957616/219805091-7283272d-5e14-441d-86a6-5b3e40ec4543.png)

1. Have pages 'Foo' and 'Foo/Bar'
2. Go on 'Foo/Bar'
3. No breadcrumbs

## Expected Behavior
I expect to see breadcrumbs that will allow me to get to the upper pages

## System
_Please complete the following information:_
 - MediaWiki version: 1.39.1
 - Server OS: Ubuntu 22.04.1 LTS
 - Installed extensions and versions [Special:Version](https://mtrwiki.murs-mc.ru/wiki/%D0%A1%D0%BB%D1%83%D0%B6%D0%B5%D0%B1%D0%BD%D0%B0%D1%8F:%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F)
 - PHP version 8.1.16 (fpm-fcgi)

**Comment by alistair3149** [comment]
Citizen doesn't control that subpage output, it seems that is something else that is causing it.

**Comment by WerySkok** [comment]
Oh, my bad:
> By default, MediaWiki's subpage feature is turned off in the main namespace...

https://www.mediawiki.org/wiki/Help:Subpages
