### ISSUE TITLE
Highlighted lines in <syntaxhighlight> blocks are too bright in dark mode.

### ISSUE THREAD

**Issue by WerySkok** [StarCitizenTools/mediawiki-skins-Citizen#593]
## Describe the Bug
When using ``<syntaxhighlight>`` tag from [SyntaxHighlight](https://www.mediawiki.org/wiki/Extension:SyntaxHighlight) extension on my wiki I have found that highlighted lines are not adapted for dark mode. Also highlighted background doesn't cover the whole line if it's too long.

[Example](https://mtrwiki.murs-mc.ru/wiki/Nemo%27s_Transit_Expansion/%D0%94%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_%D0%BF%D0%BE%D0%BB%D0%B8%D0%B3%D0%BE%D0%BD%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D1%85_%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D0%B5%D0%B9#%D0%A0%D0%B0%D0%B7%D0%BD%D1%8B%D0%B5_%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D0%B8_%D1%83_%D1%80%D0%B0%D0%B7%D0%BD%D1%8B%D1%85_%D0%B2%D0%B0%D0%B3%D0%BE%D0%BD%D0%BE%D0%B2).

![изображение](https://user-images.githubusercontent.com/15957616/219873762-c01e843f-98d8-4a61-a069-a30746e0e9fa.png)
![изображение](https://user-images.githubusercontent.com/15957616/219873772-62166829-4cbe-4224-bfd1-992c140bfa12.png)

1. Have SyntaxHighlight extension enabled on a wiki.
1. Turn on dark mode.
2. Create a page with ``<syntaxhighlight>`` block that also uses ``highlight`` parameter. For example: 
```html
<syntaxhighlight lang="json" highlight="7">
{
  "custom_trains": {
    "lu1995": {
      "name": "LU 1995",
      /* ... пропущены параметры, использование которых не отличается */
      "texture_id": "mtrsteamloco:textures/block/nte_tile_faded.png",
      "model": "mtr:lu1995/modeltrain_1995_tube_train.obj|1;%1;|mtr:lu1995/modeltrain_1995_tube_train_carriage.obj|;1,-1;|mtr:lu1995/modeltrain_1995_tube_train.obj|-1;%1,1;reversed",
      "model_properties": "mtr:lu1995/properties.json"
    }
  }
}
</syntaxhighlight>
```

## Expected Behavior
Highlighted background should not be that bright and also should cover the whole line.

## System
_Please complete the following information:_
 - MediaWiki version: 1.39.1
 - Server OS: Ubuntu 22.04.1 LTS
 - Installed extensions and versions [Special:Version](https://mtrwiki.murs-mc.ru/wiki/%D0%A1%D0%BB%D1%83%D0%B6%D0%B5%D0%B1%D0%BD%D0%B0%D1%8F:%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F)
 - PHP version 8.1.16 (fpm-fcgi)

**Comment by alistair3149** [comment]
Will look into it

**Comment by WerySkok** [comment]
I see that it was solved in https://github.com/StarCitizenTools/mediawiki-skins-Citizen/commit/a269d35dac94bfe3e54703b2c80ca0de2eacdbfa, thanks!

**Comment by alistair3149** [comment]
I knew the issue was opened somewhere but I couldn't find it haha. Thanks for update it!
