### ISSUE TITLE
VisualEditor is not work.

### ISSUE THREAD

**Issue by JyunWaan** [StarCitizenTools/mediawiki-skins-Citizen#594]
## Describe the Bug
A clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem.

1. Click page VE edit button
2. Url changed
3. VE doesn't load

## Expected Behavior
Click page VE edit button, url changed but VE doesn't load.

## System
_Please complete the following information:_
 - MediaWiki version [1.39.1]
 - Server OS: Miraheze Wiki farm
 - Installed extensions and versions Unkonw
 - PHP version Unkonw

**Comment by alistair3149** [comment]
Do you have a link of the page with the issue? I can't reproduce it on other Miraheze wikis.

**Comment by JyunWaan** [comment]
This Miraheze wiki: https://nijigen.wiki/
Pages that can use VE can't be used normally.

**Comment by JyunWaan** [comment]
Oh, I open in incognito mode and it worked fine.
Maybe it's an extension problem with my browser.
