### ISSUE TITLE
 Deprecated: mb_convert_encoding():

### ISSUE THREAD

**Issue by krolingo** [StarCitizenTools/mediawiki-skins-Citizen#601]
Deprecated: mb_convert_encoding(): Handling HTML entities via mbstring is deprecated; use htmlspecialchars, htmlentities, or mb_encode_numericentity/mb_decode_numericentity instead in /usr/local/www/mediawiki/vendor/wikimedia/html-formatter/src/HtmlFormatter.php on line 94

<h2 id="mw-version-software" style="margin: 2em 0px 0.25em; color: var(--color-base--emphasized); font-weight: var(--font-weight-semibold); line-height: var(--line-height-xs); font-size: var(--font-size-h2); font-family: Roboto, &quot;Noto Sans CJK&quot;, system-ui, -apple-system, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="mw-headline" id="Installed_software">Installed software</span></h2>

Product | Version
-- | --
MediaWiki | 1.39.2
PHP | 8.2.0 (fpm-fcgi)
MySQL | 5.7.40-log
ICU | 72.1
Pygments | 2.11.2

Installed software
Product	Version
[MediaWiki](https://www.mediawiki.org/)	1.39.2
[PHP](https://php.net/)	8.2.0 (fpm-fcgi)
[MySQL](https://www.mysql.com/)	5.7.40-log
[ICU](https://icu.unicode.org/)	72.1
[Pygments](https://pygments.org/)	2.11.2

I have this error displayed on all pages. How can I fix or hide?

**Comment by alistair3149** [comment]
It is a MediaWiki upstream issue with PHP 8.2 being tracked in  [T324170](https://phabricator.wikimedia.org/T324170). I'll implement a temporary fix until [T330528](https://phabricator.wikimedia.org/T330528) is resolved.

**Comment by alistair3149** [comment]
Would you mind to check if you have the same error on special pages?
And also do you have MobileFrontend enabled? There are a few other extensions that can cause the same error as well.

**Comment by krolingo** [comment]
I disabled comments on php.ini issue solved for now...
