### ISSUE TITLE
Enhance the support for non-Latin input methods for serch input boxes

### ISSUE THREAD

**Issue by Dome-World** [StarCitizenTools/mediawiki-skins-Citizen#608]
## The Problem
Many languages are input using input methods, such as Chinese and Japanese. During the process of inputting Pinyin in Chinese, the following search box will prompt that the article was not found, but I haven't finished typing because I'm just inputting Pinyin.

## The Solution
Please adding Composition Events to the Search System enhance the support for non-Latin input methods for input boxes.

You only need to add the  Compositionend  Events  to judgment sentences with search [results. length>0]

**Comment by alistair3149** [comment]
Thanks for the suggestion! I will be looking into it.
