### ISSUE TITLE
Sometimes there is a brief white screen problem during the webpage loading process

### ISSUE THREAD

**Issue by Dome-World** [StarCitizenTools/mediawiki-skins-Citizen#609]
## Describe the Bug
When trying to open several articles, sometimes a brief white screen problem will appear during the loading process. This time itself is very short, but sometimes it can become very long. The default skin of vector was no such problem. Although the impact is not significant, it can sometimes bring a bad experience to the viewer. 

[Your official website](https://star-citizen.wiki/) also has this problem. You can try to open several articles and it will appear (10% probability) .

## Expected Behavior
Non-smooth problem of webpage loading be improved. For example, using technologies such as AJAX? This may also prevent the sidebar settings button from reloading.

## System
Tried on Edge 111.

**Comment by alistair3149** [comment]
Unfortunately with how MediaWiki is set up, that isn't a clean way to do partial loading that I know of.
Vector might not have the same issue as it has less styles and it uses white as background, so the FOUC isn't that apparent.

I am constantly looking at improving the performance of the skin, and this will be worked on continuously. However, I don't really have a clean cut solution that can be implemented at the skin-side at the moment.

**Comment by Dome-World** [comment]
I previously wrote some code that can implement this feature, but it has some problems. For example, the visual editor cannot be used on newly generated pages and there is a delay in loading CSS. However, if it can provide some ideas for your future work, it would be great.


```
function loadNewContent(url) {
  // Show loading indicator
  document.documentElement.classList.add('citizen-loading');

  var xhr = new XMLHttpRequest();
  xhr.onreadystatechange = function() {
    if (this.readyState == 4 && this.status == 200) {
      // Replace content with new content
      var newContent = document.createElement('div');
      newContent.innerHTML = this.responseText;
      var newContentDiv = newContent.querySelector('#content');
      content.innerHTML = newContentDiv.innerHTML;

      // Hide loading indicator
      document.documentElement.classList.remove('citizen-loading');

      // Update browser history
      history.pushState(null, null, url);

      // Load and parse new CSS files
      var newCSSFiles = newContent.querySelectorAll('link[rel="stylesheet"]');
      newCSSFiles.forEach(function(file) {
        var newLink = document.createElement('link');
        newLink.rel = 'stylesheet';
        newLink.href = file.href;
        document.head.appendChild(newLink);
      });
    }
  };
  xhr.open('GET', url, true);
  xhr.send();
}

// Attach click event listener to all links
var links = document.querySelectorAll('a');
var content = document.getElementById('content');
links.forEach(function(link) {
  link.addEventListener('click', function(e) {
    e.preventDefault();
    loadNewContent(this.href);
  });
});

// Attach popstate event listener to handle back/forward navigation
window.addEventListener('popstate', function(e) {
  loadNewContent(location.href);
});
```

**Comment by alistair3149** [comment]
Yes the issue is because the CSS and JS needed on each page is generated dynamically into a single request with ResourceLoader. You have to wait for server regardless to load the appropriate styles or scripts unfortunately.

The HTML on each page might not be the same outside of `#content` as well. So there aren't really good solutions on the skin side that I know of to tackle this.

The stylesheet is already decently sized and very high in the critical rendering queue, so the stylesheet might have loaded too slowly. It could be caused by cache miss, server performance, or connection issues. I would suggest looking into those areas to see if any improvements can be made.

Lastly, would you be able to test other skins that also have a dark mode? I suspect that Vector shares the same issue, but it is not visible because it has a white background.

**Comment by Dome-World** [comment]
well, I think you can see this website: https://www.isekai.cn
It achieved what I said.

**Comment by Dome-World** [comment]
> Yes the issue is because the CSS and JS needed on each page is generated dynamically into a single request with ResourceLoader. You have to wait for server regardless to load the appropriate styles or scripts unfortunately.
> 
> The HTML on each page might not be the same outside of `#content` as well. So there aren't really good solutions on the skin side that I know of to tackle this.
> 
> The stylesheet is already decently sized and very high in the critical rendering queue, so the stylesheet might have loaded too slowly. It could be caused by cache miss, server performance, or connection issues. I would suggest looking into those areas to see if any improvements can be made.
> 
> Lastly, would you be able to test other skins that also have a dark mode? I suspect that Vector shares the same issue, but it is not visible because it has a white background.
Well, I think you can see this website: https://www.isekai.cn
It achieved what I said. But I don't know how he achieved it.

**Comment by Dome-World** [comment]
I asked him, it was just an onbeforeunload animation, nothing more.
