### ISSUE TITLE
Menu Icons of "Special pages" and "Upload file" can't show

### ISSUE THREAD

**Issue by AlanYe-Dev** [StarCitizenTools/mediawiki-skins-Citizen#617]
## Describe the Bug
The icons of Special Pages and Upload file can't show up in the menu (drawer)
Even [StarCitizenTools](https://starcitizen.tools/) has this problem.

## Expected Behavior
These icons can show normally in Citizen v1 skin.

**Comment by alistair3149** [comment]
It is a known issue that I'm looking into, but I haven't figured out a way to add those icon properly. In the meantime, you can implement a similar fix in MediaWiki:Citizen.css: https://theapplewiki.com/wiki/MediaWiki:Citizen.css#L-196

**Comment by alistair3149** [comment]
Closed with e771c728e16624cbf85b6fcc1c9d5d661a104075
