### ISSUE TITLE
Page overflow when using indicators excessively

### ISSUE THREAD

**Issue by labster** [StarCitizenTools/mediawiki-skins-Citizen#635]
I'm testing out on another wiki, and we have one page with all of the available `{{Top icon}}`s.   One long row of icons makes the page title shrink down to a character of one column, Chinese style, so it can fit all of the top icons in.

Is this a dumb thing to do?  Probably. The fix seems easy, though. Adding this seems to help:
```
.mw-indicators {
  flex-wrap: wrap;
}
```

**Comment by labster** [comment]
<img width="1345" alt="Screen Shot 2023-05-26 at 8 20 21 PM" src="https://github.com/StarCitizenTools/mediawiki-skins-Citizen/assets/108723/144c3e41-bd1b-4ea7-8390-f1fc4078a32e">

There's a second bug in this screenshot as well, in the table of contents.  The italic text gets flowed as a separate element.  Is there a good reason that ``citizen-toc__text` has `display: flow`?  I don't think it needs it.

**Comment by alistair3149** [comment]
Would you mind to link me to the page with the issue?

**Comment by labster** [comment]
Do you have a Miraheze account?  It's on a private wiki, so I'd have to give you access.  (There's nothing really all that private in there; it would be a public wiki if Miraheze was located in Canada, but we can't make it public because Miraheze is located in the U.K.)

https://theresnothingbetter.miraheze.org/wiki/Mary_Sue

**Comment by alistair3149** [comment]
Yeah I have an account under the same name on Miraheze. It would be helpful if I can see a live demo and I can work out on how to resolve it quickly :)

**Comment by labster** [comment]
Sure.  You have to actually visit the wiki while logged in before I can assign userrights.  That's the way CentralAuth works.

**Comment by labster** [comment]
you should have access now
