### ISSUE TITLE
Lengthy page title pushes page action menu to the left

### ISSUE THREAD

**Issue by Rasputin93** [StarCitizenTools/mediawiki-skins-Citizen#648]
Hello, I've disabled the visibility of the "normal" buttons for edit, history and such for anon users, which would result in only leaving the page action menu visible. So far, no issue... unless the page title is lengthy, which moves the menu to the left and out of reach on mobile view. [Here's the page in question.](https://rammwiki.net/wiki/Main_Page)

I did a quick and dirty fix in my CSS in the meantime, but I'd prefer a change in the core to make sure it won't be affected by other changes in future versions. The screenshot does not display my fix, but rather how it's displayed without.

![Screenshot_20230602_135206_Firefox](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/assets/25199548/19955630-7105-4942-b92c-8e8e2d5e27d8)

**Comment by alistair3149** [comment]
Thanks for the report! I'll look into it
