### ISSUE TITLE
Add support for tabs

### ISSUE THREAD

**Issue by ananpanang-png** [StarCitizenTools/mediawiki-skins-Citizen#687]
## The Problem
The skin doesn't support Tabs from Extension:Tabs in dark mode.
The background is still white, but the text is inverted color.

![Screenshot_20230711-185010_Kiwi Browser](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/assets/114722355/5e4c0bd6-b4b6-4bb6-b8c8-6d056c84a045)

## The Solution
Maybe change the background to dark gray, similar to tables, and leave the text color the same light blue.

**Comment by alistair3149** [comment]
Do you have a sample page with the extension?

**Comment by ananpanang-png** [comment]
https://astronomy.wikitide.com/wiki/
