### ISSUE TITLE
Rendering issues after using custom JS, or editing LocalStorage.

### ISSUE THREAD

**Issue by thatgaypigeon** [StarCitizenTools/mediawiki-skins-Citizen#691]
> _First I would like to clarify that I suppose this is not technically a bug. Also, it is only achievable either through custom JS or by using dev tools. As (almost) anyone who could cause this issue could also resolve it themselves, I don't know if it is a major enough issue to warrant a fix, but hey-ho. :)_

## Describe the Bug
Any other value than `auto` or `light` in LocalStorage for `skin-citizen-theme` will cause issues while rendering the page (on reload).

Steps to reproduce the behaviour:
1. Open dev tools
2. Click on `Application` (top tab)
3. Click on `LocalStorage` (sidebar), then `https://starcitizen.tools/`
4. Change the value for key `skin-citizen-theme` to anything other than `light` or `auto`
5. Reload the page
> _Note: This can also be recreated by using custom JS (how I initially discovered this issue)._

This will cause colour issues, but importantly, it causes a JavaScript error when trying to open the Preferences (Appearance) tab in the left sidebar.
```
Uncaught TypeError: Cannot set properties of null (setting 'checked') at HTMLButtonElement.initPanel (<anonymous>:6:796)
```
This prevents the value from being changed back again.

Other values, such as for font-size do not cause this issue. They just max out the slider but still allow the `<aside>` element to open. Users can then still edit the appearance values as normal.

## Expected Behavior

The page does not break.

## Suggested fix
A simple fix (I believe) would be adding in a check on page load to change the value to `auto` if it is set to anything other than `auto`, `light`, `dark`, or if it is unset. This would ensure that any shenanigans with custom JS or dev tools wouldn't break the page.

**Comment by alistair3149** [comment]
Thanks for the detailed explanations! It is indeed an unintended bug that stemmed from my hacky implementation of theme switch way back :/

Citizen was supposed to be able to support more themes but I haven't had time to implement the functionality yet. I'll refactor the preferences menu hopefully in these two weeks

**Comment by alistair3149** [comment]
No longer relevant now as the underlying codes have been completely refactored. Closing the issue now.
