### ISSUE TITLE
Option to disable html sanitization in "sidebar" menu

### ISSUE THREAD

**Issue by Xenorio** [StarCitizenTools/mediawiki-skins-Citizen#706]
## The Problem
I could not find a way to add custom icons to buttons in the sidebar, so any custom button looks very out of place. When putting custom html in the MediaWiki:Sidebar page, for example an "i" tag for FontAwesome, this html gets sanitized and displayed as plain text.

## The Solution
A config option that disables certain sanitization would be great. Of course it should not be enabled by default, but users who know what they're doing should be allowed to add things where they want to.

I am not asking for native FontAwesome integration here, as it already got rejected at https://github.com/StarCitizenTools/mediawiki-skins-Citizen/issues/175, but sanitizing everything away is actively preventing custom integration.

## The Alternatives
I did implement a sketchy little workaround which technically does the job, but is still sketchy:

**MediaWiki:common.css**
```
@import "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
```

**MediaWiki:common.js**
```
$(document).ready(function() {
    // Sidebar Menu Icons
    $('#n-Substances a').prepend('<i class="fas fa-flask"></i> ');
    $('#n-Categories a').prepend('<i class="fas fa-list"></i> ');
});
```

**Comment by alistair3149** [comment]
The sidebar handling and sanitization does not happen within Citizen, the content related to `MediaWiki:Sidebar` is processed by MediaWiki core. I would suggest submitting a [feature request](https://phabricator.wikimedia.org/maniphest/task/edit/form/102/) to Wikimedia Phabricator to request for some kind of skin-wide icon support for sidebar.

However for now, using a MediaWiki PHP hook (which will be added to the cached HTML directly) or Javascript would be the best way.
