### ISSUE TITLE
.citizen-scroll--down .citizen-header - Help wanted

### ISSUE THREAD

**Issue by RothwellWiki** [StarCitizenTools/mediawiki-skins-Citizen#713]
Hello,

I was hoping someone could help me figure out how to remove the transformation of the header that makes it disappear when scrolling on mobile. I added:
```
@media screen and (max-width: 720px) {
   .citizen-scroll--down .citizen-header {
        transform: translateY(0%);
     }
}
```
to the [MediaWiki:Commons.css page](https://www.rothwell-leeds.co.uk/wiki/MediaWiki:Common.css) which fixed the issue on small screens when you toggle desktop view (e.g [here](https://www.rothwell-leeds.co.uk/w/index.php?title=Katherine_Earle&mobileaction=toggle_view_desktop)) but not when you toggle mobile view (e.g [here](https://www.rothwell-leeds.co.uk/w/index.php?title=Katherine_Earle&mobileaction=toggle_view_mobile)). Would someone be able to suggest how I might fix this?

Thanks for all your help!

**Comment by alistair3149** [comment]
You also need the same rules on MediaWiki:Mobile.css when you use MobileFrontend, since MobileFrontend will not load styles from MediaWiki:Common.css

**Comment by RothwellWiki** [comment]
Thanks very much!:)
