### ISSUE TITLE
Extra wide desktop styles

### ISSUE THREAD

**Issue by alistair3149** [StarCitizenTools/mediawiki-skins-Citizen#74]
Optimize the UI for screen size wider than 2000px by allowing content to occupy part of the unused whitespace.

**Comment by diablo6006** [comment]
You can add the css role to your Mediawiki:common.css

@media only screen and (max-width: 2000px) {
.mw-body-content {
    max-width: 70em;
}
}
note: change the max-width as required, this example works well with 1366px screens. in your case i guess settings it to 80em is good.

**Comment by diablo6006** [comment]
sorry, I didn't know that you are a member of development team

**Comment by alistair3149** [comment]
Done in the layout refactor recently
