### ISSUE TITLE
Icons not showing on MediaWiki version 1.39.5

### ISSUE THREAD

**Issue by ItsGamingTube** [StarCitizenTools/mediawiki-skins-Citizen#757]
## Describe the Bug
Most of the icons on the wiki does not show at all.

1. Install MediaWiki Verison 1.39.5
2. Install the skin
3. See the results

## Expected Behavior
The icons should be visible and should be showing normally.

## System
 - MediaWiki version: 1.39.5
 - Server OS: Unknown (Shared Hosting)
 - Installed extensions and versions: N/A (fresh copy of MediaWiki installed using Softaculous, just the Citizen skin installed)
 - PHP version: 8.1

Website link: https://swordigowiki.cf

**Comment by alistair3149** [comment]
There are some server configuration issue on your end with redirects, and it is unrelated to the skin.
Most of the icons are returning `HTTP 508`, but I am not sure what exactly caused it.
