### ISSUE TITLE
Add option to revert new Recent Changes page style

### ISSUE THREAD

**Issue by WerySkok** [StarCitizenTools/mediawiki-skins-Citizen#764]
## The Problem
While new Recent Changes style may look cool or beautiful, it isn't comfortable to use it because now I have to stretch my eyes across the whole monitor just to see the changes delta number.

![изображение](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/assets/15957616/26550b37-2e58-4118-abeb-2a27caebd6be)

## The Solution
Add an option for users to return the old style. For example, this setting can be added to user's preferences page or on the Recent Changes page itself.

## The Alternatives
This option shouldn't be set up only by the admins of the wiki (by making it changeable only with LocalSettings.php) because it's better to give users an option to change this behavior.

Another option would be reverting all these changes, but I'm sure this wouldn't be a popular option.

**Comment by alistair3149** [comment]
I'll look into adding the config to toggle the behavior next week. It'll be a site-wide config in the initial implementation, and it'll be switched to a user config later as I have to clean up client preferences before the next MW LTS.
