### ISSUE TITLE
$wgCitizenThemeDefault as auto shows white theme

### ISSUE THREAD

**Issue by Mr-Arceni** [StarCitizenTools/mediawiki-skins-Citizen#767]
## Describe the Bug
When `$wgCitizenThemeDefault` is set to `auto`, a white theme is shown when entering the wiki (_according to system settings, a dark theme is expected_). In the theme settings tab, "Auto" is selected, but the theme changes automatically only after manually clicking on "Auto"

1. Have a default value for a parameter `$wgCitizenThemeDefault`
2. Visit the wiki for the first time
3. See white theme (_dark theme expected_)

## Expected Behavior
Fully automatic switching to a dark theme is expected, according to system settings.

## System
 - MediaWiki version 1.40.1
 - Server OS: unknown
 - Installed extensions and versions: CodeEditor, CodeMirror 4.0.0 (817396c), VisualEditor 0.1.2, VisualEditor 0.1.2, CategoryTree, Cite, ImageMap, InputBox 0.3.0, Math 3.0.0, ParserFunctions 1.6.0, Poem, Scribunto, SyntaxHighlight 2.0, TemplateData 0.1.2, TemplateStyles 1.0 (9699f28), Abuse Filter, ConfirmEdit 1.6.0, SpamBlacklist, TitleBlacklist 1.5.0, PageImages, Gadgets, MultimediaViewer, Popups (e04ff11), SandboxLink (d8e0db0), SecureLinkFixer, TextExtracts.
 - PHP version 8.1.25 (apache2handler)

**Comment by alistair3149** [comment]
Should be fixed in the latest version. Please feel free to re-open the issue if it happens again :)
