### ISSUE TITLE
Document Extension:PageImages support

### ISSUE THREAD

**Issue by ProbablePrime** [StarCitizenTools/mediawiki-skins-Citizen#799]
## The Problem
It was not clear to me that this skin supported Extension:PageImages, a search in the repository revealed just one reference to it and the rest had to be done by digging through the code.

## The Solution
Add documentation that details the support for this extension. Similar to: https://github.com/StarCitizenTools/mediawiki-skins-Citizen#search-suggestions

## The Alternatives
Continuing to be confused :'(?

**Comment by alistair3149** [comment]
Citizen is just using the [search endpoint](https://www.mediawiki.org/wiki/API:REST_API/Reference#Search) provided by the REST API from MediaWiki by default. The thumbnail in that API can be fed by multiple sources, one being Extension:PageImages. So essentially Citizen is directly related to Extension:PageImages in any way, as both sides are interfacing with MediaWiki core instead of each other

**Comment by ProbablePrime** [comment]
Agreed, but some documentation here detailing the options would be appreciated.

**Comment by alistair3149** [comment]
I will be looking into adding documentation for recommended optional extensions to go with Citizen. For search specifically, it is still a work in progress with a lot of improvements planned, so I am more inclined to wait till it to be stable before adding documentation.

**Comment by ProbablePrime** [comment]
@MedicineStorm alistair added the recommended extensions here: https://github.com/StarCitizenTools/mediawiki-skins-Citizen#recommended-extensions

This meets my confusion and solves it, but im unsure if it solves yours. If you're having issues with the search icons you may need to open a separate issue here or on the extension that is missbehaving.

@alistair3149 THANK YOU

**Comment by MedicineStorm** [comment]
@ProbablePrime I appreciate the information, but it does not solve my own issue. However, this extension seems to work well enough for my needs. A bit quirky as well, but far more direct for designating a page/search icon: https://www.mediawiki.org/wiki/Extension:Title_Icon

Thanks again.
