### ISSUE TITLE
Update compatibility for SemanticMediaWiki 4.1.x

### ISSUE THREAD

**Issue by greezlu** [StarCitizenTools/mediawiki-skins-Citizen#804]
## The Problem
Support for old **SemanticMediaWiki** `4.0.2`. This version is not compatible with `php >= 8.1` [issue #5385](https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/5385). I know later versions will probably work fine but I'm a little paranoid)
https://github.com/StarCitizenTools/mediawiki-skins-Citizen/blob/4aabfda54d68efb97770adc5b6aa2e80fe03c49a/README.md?plain=1#L74

## The Solution
I'm asking to confirm compatibility with `4.1.x` versions of **SemanticMediaWiki** as that was [the point](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/b5e2afe11991fe21a335cb90426de24b85bc9fe7/docs/COMPATIBILITY.md?plain=1#L40) to start supporting `php8.1`.

**Comment by alistair3149** [comment]
The version on the table is not for compatibility, but simply stating the version of the extension when the CSS is imported. Extensions don't usually change their styles so it is compatible most of the time. Even if it is not, there won't be any breaking changes, just missing styles.
