### ISSUE TITLE
The theme icons are suddenly missing

### ISSUE THREAD

**Issue by luffypirat** [StarCitizenTools/mediawiki-skins-Citizen#805]
## Describe the Bug
Hello, I would like to ask for help as I am using your wonderful theme. I have suddenly lost the control icons on the wiki, I can't figure out what could have caused this. I only have Cloudflare connected to the site.

Also I checked, your theme is breaking my craft template for some reason, on another theme it works fine. Could you please help to fix it for me? I would be very grateful!!!

Template ex: https://createwiki.ru/wiki/%D0%98%D0%BD%D0%B6%D0%B5%D0%BD%D0%B5%D1%80%D0%BD%D1%8B%D0%B5_%D0%BE%D1%87%D0%BA%D0%B8

1. open any page
2. Control icons are missing from the page
3. although they should be

## Expected Behavior
Everything should load

## System
_Please complete the following information:_
 - MediaWiki version v1.40
 - Server OS: Debian 11
- https://createwiki.ru/wiki/%D0%A1%D0%BB%D1%83%D0%B6%D0%B5%D0%B1%D0%BD%D0%B0%D1%8F:%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F
 -  8.3.3-1+0~20240216.17+debian11~1.gbp87e37b (cli) (built: Feb 16 2024 10:33:07) (NTS)
<img width="269" alt="msedge_e6AqrmSzie" src="https://github.com/StarCitizenTools/mediawiki-skins-Citizen/assets/7715278/22beedf2-293b-421c-982b-833fad3b0b39">
<img width="1254" alt="msedge_ENSa5g8LL3" src="https://github.com/StarCitizenTools/mediawiki-skins-Citizen/assets/7715278/5235bda1-180e-4f71-b1aa-5e0c12f02a71">

**Comment by luffypirat** [comment]
`2024/03/03 00:02:36 [warn] 24018#24018: *3 an upstream response is buffered to a temporary file /var/cache/nginx/fastcgi_temp/1/00/0000000001 while reading upstream, client: 94.25.238.213, server: createwiki.ru, request: "GET /load.php?lang=ru&modules=ext.echo.styles.badge%7Cext.visualEditor.desktopArticleTarget.noscript%7Coojs-ui.styles.icons-alerts%7Cskins.citizen.icons%2Cstyles%7Cskins.citizen.icons.wmui&only=styles&skin=citizen HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm.sock:", host: "createwiki.ru", referrer: "https://createwiki.ru/wiki/%D0%97%D0%B0%D0%B3%D0%BB%D0%B0%D0%B2%D0%BD%D0%B0%D1%8F_%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0"
2024/03/03 00:02:37 [warn] 24018#24018: *39 an upstream response is buffered to a temporary file /var/cache/nginx/fastcgi_temp/2/00/0000000002 while reading upstream, client: 94.25.238.213, server: createwiki.ru, request: "GET /load.php?lang=ru&modules=jquery&skin=citizen&version=3ozn9 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm.sock:", host: "createwiki.ru", referrer: "https://createwiki.ru/wiki/%D0%97%D0%B0%D0%B3%D0%BB%D0%B0%D0%B2%D0%BD%D0%B0%D1%8F_%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0"
`

**Comment by luffypirat** [comment]
My nginx error log

**Comment by alistair3149** [comment]
I looked at one of the icons and it seems that there is some sort of XML error with the SVG:
https://createwiki.ru/load.php?modules=skins.citizen.icons.wmui&image=userAdd&format=original&lang=ru&skin=citizen&version=zpbhi

I don't know what can be causing that, but I am not sure if it is related to the skin since the skin only requests the icon from MediaWiki using the method provided. It could be an issue with MediaWiki itself or its dependencies. Has anything changed recently that might have caused this?

**Comment by luffypirat** [comment]
@alistair3149 
I noticed this when I added the WelcomeMessage and Create User Page extensions. Usually, if any extensions partially or completely broke the site, disabling them brought everything back to normal. I also checked the site on a new MediaWiki installation with a new database and everything works correctly there. Can you check my LocalSetting file for errors? Thanks!

**Comment by luffypirat** [comment]
And locally uploaded SVG files are displayed, as well as from Wikimedia Commons

**Comment by luffypirat** [comment]
And the most puzzling thing is that Google Chrome for Android loads the icons without error, at first I thought they were just left in the cache, but after clearing it they loaded again, also from it there is no error in the link you sent to me

**Comment by luffypirat** [comment]
I found the problem! It turns out I accidentally put an extra Tab at the very beginning of LocalSettings `<?php!`
Now everything works! Thanks for pointing me in the right direction for a solution!
