### ISSUE TITLE
Call to undefined method MediaWiki\Extension\TemplateStyles\TemplateStylesMatcherFactory::cssSingleTimingFunction()

### ISSUE THREAD

**Issue by aolko** [StarCitizenTools/mediawiki-skins-Citizen#806]
## Describe the Bug
RE: https://github.com/octfx/mediawiki-extensions-TemplateStylesExtender/issues/17

1. Update MW to 1.41
2. Update extensions
3. Update citizen

## Expected Behavior
Normal work with `TemplateStylesExtender` extension

## System
_Please complete the following information:_
 - 1.41.0
 - `Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-97-generic x86_64)`
 - 
 ```AbuseFilter
Linter
ReplaceText
CategoryTree
LocalisationUpdate
Scribunto
Cite
LoginNotify
SecureLinkFixer
CiteThisPage
Math
SpamBlacklist
CodeEditor
MultimediaViewer
SyntaxHighlight_GeSHi
ConfirmEdit
NewestPages
TabberNeue
CSS
Nuke
TemplateData
DiscussionTools
OATHAuth
TemplateStyles
Echo
PageImages
TemplateStylesExtender
Gadgets
ParserFunctions
TextExtracts
HitCounters
PdfHandler
Thanks
ImageMap
Poem
TitleBlacklist
InputBox
Popups
VisualEditor
Interwiki
PortableInfobox
Wikibase
LinkCards
RelatedArticles
WikiEditor
LinkCards
Renameuser
 ```
 - PHP 8.1.27

**Comment by alistair3149** [comment]
Not related to Citizen, the log points to Extension:TemplateStylesExtender.
