### ISSUE TITLE
Loading indicator isn't removed when using browser navigation

### ISSUE THREAD

**Issue by Marlamin** [StarCitizenTools/mediawiki-skins-Citizen#811]
## Describe the Bug
Pretty much the exact same issue from #718 that appears to be back. Loading indicator doesn't go away when using browser navigation.

1. Go to any page 
2. Click on any link to a different page
3. Use mouse buttons or browser buttons to navigate backwards (or forwards for that matter)
4. Loading indicator stays.

## Expected Behavior
No loading indicator after navigating and page finished loading.

## System
Chrome 122.0.6261.129 on Windows 11
MediaWiki 1.39.6
Citizen 2.10.1

**Comment by alistair3149** [comment]
Thanks for the report. Would you be able to provide a demo page with the issue?

**Comment by Marlamin** [comment]
Go to https://starcitizen.tools/
Browse to https://starcitizen.tools/Ships
Hit back 

Happens on Desktop and Mobile with no extensions enabled.
