### ISSUE TITLE
Background Colour Changed from White to Grey

### ISSUE THREAD

**Issue by RothwellWiki** [StarCitizenTools/mediawiki-skins-Citizen#819]
## Describe the Bug
Unexpected change in the background colour of my [wiki](https://www.rothwell-leeds.co.uk).
This happened either after I changed $wgMFCollapseSectionsByDefault to false, or after I added Extension:PageNotice. Unsure if it's related though. I tried to fix it by changing $wgCitizenThemeColor as I didn't understand what this did. Now I know it won't make any difference.

Before
`   --color-surface-0: hsl(0,0%,100%);
--color-surface-1: hsl(0,0%,100%);
...`
After
`--color-surface-0: hsl(var(--color-primary__h),25%,94%);
--color-surface-1: hsl(var(--color-primary__h),30%,92%);
...`

Unknown.

## Expected Behavior
It should have been white, but it was instead greyish.

## System
 - MediaWiki version: 1.41.0
 - Server OS: Unknown (hosted by Miraheze)
 - Installed extensions and versions: see [Special:Version](https://www.rothwell-leeds.co.uk/wiki/Special:Version)
 - PHP version: 8.2.7 (fpm-fcgi)

**Comment by alistair3149** [comment]
It is an intended change introduced with v2.11.0. The light theme colors are reworked to be less bright and more influenced by the primary color of the wiki. You can redefine the surface colors in CSS if you prefer.

**Comment by BeckeBauer** [comment]
I don't get it - what is the "primary color of the wiki"? I liked the content to be on a white background (light theme). I would like to change my "primary color" to white if this changes my background back to white - how can I achieve it (ideally without having to manipulate CSS since I have no clue how to do it)?

**Comment by alistair3149** [comment]
> What is the "primary color of the wiki"?

The [primary color](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/wiki/Customizing-Citizen-styles#primary-color) is the blue color you see typically in UI elements like the edit button.  It is used to influence the colors used by the dark theme, and now it has been extended to the light theme as well.

> How can I achieve it (ideally without having to manipulate CSS since I have no clue how to do it)?

Unfortunately Citizen is heavily CSS-based, almost all customizations are done through CSS. If you just want to change your background color to white, you can put this in your `MediaWiki:Citizen.css`  page on your wiki:
```css
:root {
    --color-surface-0: #fff;
}
```

**Comment by BeckeBauer** [comment]
> > What is the "primary color of the wiki"?
> 
> The [primary color](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/wiki/Customizing-Citizen-styles#primary-color) is the blue color you see typically in UI elements like the edit button. It is used to influence the colors used by the dark theme, and now it has been extended to the light theme as well.
> 
> > How can I achieve it (ideally without having to manipulate CSS since I have no clue how to do it)?
> 
> Unfortunately Citizen is heavily CSS-based, almost all customizations are done through CSS. If you just want to change your background color to white, you can put this in your `MediaWiki:Citizen.css` page on your wiki:
> 
> ```css
> :root {
>     --color-surface-0: #fff;
> }
> ```

Did not expect it to be that easy to modify; thank you!
