### ISSUE TITLE
Have an option to put page actions in sidebar

### ISSUE THREAD

**Issue by TimothyAtTheArcade** [StarCitizenTools/mediawiki-skins-Citizen#821]
## The Problem
First, I want to begin by saying I am in the process of adapting this skin for my wiki and I'm loving it! I love the user-centric features like being able to change page width, font size, etc. One thing I have noticed when the screen size is narrow, the page actions element (Page history, edit this page, edit source, discussion, ellipsis for more options) in the body header wraps to a second line when there is not enough room for the article title and the page actions.
## The Solution
I would love it if there was an option or flag you could set to put the page actions in the citizen-header sidebar. The icons would already fit the sidebar well in terms of styling. There might be an issue with all of them not fitting on the sidebar when you get to a certain width, but they could be collapsed into a menu, scrollable, or you could apply a display:none to certain ones at a certain breakpoint. Since in most cases this would be on small device like a mobile phone, the screen could be rotated if one needed to access an option that was hidden.

## The Alternatives
Another possible option would be if there was a way to know when page actions is about to wrap to a second line in the body header, and collapse it into a menu like preferences or table of contents.

**Comment by alistair3149** [comment]
Thanks for the suggestions!

My original plan was to make the page actions auto-collapse through Javascript, while keeping it in the same line as the title. It can be either a popup menu accessible through the sticky header through a three dot button, or some kind of floating action button at the bottom. There was some limitations back then but perhaps it is time to revisit the idea.

As for citizen-header, it is mainly for navigations in the site-scope, whereas page actions are page-scope and is a part of the body-header. We actually ran through great length to decouple page-scope actions (e.g. Tools menu in the more menu used to be on site navigation) from the site menu.

**Comment by alistair3149** [comment]
It is now moved to a floating toolbar at the bottom when the width is limited.
