### ISSUE TITLE
Support MediaWiki's method to add links to footer

### ISSUE THREAD

**Issue by jeffw16** [StarCitizenTools/mediawiki-skins-Citizen#823]
## The Problem
In other skins, it is possible to add custom links to the footer using hooks, following the standard procedure defined on MW.o: https://www.mediawiki.org/wiki/Manual:Footer

For instance, the following code should add the link to the footer, but on the Citizen skin, it does not:

```php
$wgHooks['SkinAddFooterLinks'][] = function ( Skin $skin, string $key, array &$footerlinks ) {
    if ( $key === 'places' ) {
        $footerlinks['test'] = Html::rawElement( 'a',
            [
                'href' => 'https://www.example.org/wiki/Project:Imprint',
                'rel' => 'noreferrer noopener' // not required, but recommended for security reasons
            ],
        $skin->msg( 'test-desc' )->text() // test-desc is an i18n message of the text
        );
    };
};
```

## The Solution
Would it be possible to add the ability to render these custom links when the hook is called?

**Comment by alistair3149** [comment]
That's very weird as it is working on our [production](https://github.com/StarCitizenTools/sct-docker-images/blob/fde5f5df4118af56161552708d7529600d033644/config/LocalSettings.php#L986) [wiki](https://starcitizen.tools/). Would you mind to share your config?

**Comment by jeffw16** [comment]
At the moment I believe this is another issue related to 1.35 -> 1.39. Sorry for the false positive.
