### ISSUE TITLE
 Warning: Array to string conversion in D:\phpstudy_pro\mediawiki-1.41.1\extensions\VisualEditor\includes\Hooks.php on line 889

### ISSUE THREAD

**Issue by Zacharia2** [StarCitizenTools/mediawiki-skins-Citizen#829]
## Describe the Bug
A clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem.

![image](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/assets/32425955/8b7b5526-7c49-4bbf-a3f3-3cdf12707b3a)

1. Install the theme according to https://www.mediawiki.org/wiki/Skin:Citizen/zh#Configuration.
2. In LocalSettings.php, set `wfLoadSkin( 'Citizen' ); $wgDefaultSkin = "Citizen";`
3. A warning appears at the top of the page.

## Expected Behavior

When I installed the Citizen theme and enabled it, a warning appeared at the very top of the page:
Warning: Array to string conversion in D:\phpstudy_pro\mediawiki-1.41.1\extensions\VisualEditor\includes\Hooks.php on line 889

## System
_Please complete the following information:_
 - MediaWiki version v1.41.1
 - Server OS: Win10
 - Installed extensions and versions SemanticMediaWiki4.1
 - PHP version PHP 8.0.2 (cli) (built: Feb  3 2021 18:36:37) ( NTS Visual C++ 2019 x64 )

**Comment by Zacharia2** [comment]
![image](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/assets/32425955/d9e41117-1780-46e2-9933-7192aa762e58)

**Comment by alistair3149** [comment]
The error doesn't come from Citizen, it is caused by VisualEditor according to the message.

**Comment by Zacharia2** [comment]
thanks
