### ISSUE TITLE
Floating edit buttons not showing up in Firefox on MW 1.41

### ISSUE THREAD

**Issue by ratte1303** [StarCitizenTools/mediawiki-skins-Citizen#834]
## Describe the Bug
When opening the wiki on mobile Firefox app the floating edit buttons are not showing. Opening on Chrome on mobile they do show up. 

## System
 - MediaWiki version 1.41
 - Server OS: Debian 11
 - Installed extensions and versions: only the skin
 - PHP version 8.1

**Comment by alistair3149** [comment]
What OS are you using?

**Comment by ratte1303** [comment]
Android

**Comment by ratte1303** [comment]
> What OS are you using?

Android

**Comment by alistair3149** [comment]
Do you have a live demo? I can't reproduce it on the same browser

**Comment by ratte1303** [comment]
> Do you have a live demo? I can't reproduce it on the same browser

todo.wwiki.org its a fresh install of MW 1.41 with only the skin changed.

**Comment by ratte1303** [comment]
<img width="562" alt="Bildschirmfoto 2024-05-05 um 08 52 26" src="https://github.com/StarCitizenTools/mediawiki-skins-Citizen/assets/151960006/928b064e-766c-4b1a-8912-2e2a15eaf3ee">

It seems to have something to do with the screen height. Putting my phone in landscape mode the buttons show up and you can see on the screenshot when changing the height of the window the buttons show up.

**Comment by alistair3149** [comment]
Would you mind to check if the latest commit fixes it?

**Comment by ratte1303** [comment]
Yep fixed it. Thanks, that was quick :)
