### ISSUE TITLE
Not possible to "click away" the drawer menu or the search menu

### ISSUE THREAD

**Issue by ratte1303** [StarCitizenTools/mediawiki-skins-Citizen#835]
## Describe the Bug
On Safari on iOS it is not possible to "click away" the drawer menu or the search menu.
Live demo: todo.wwiki.org

## Expected Behavior
When touching on empty area the menu should disappear.

## System
_Please complete the following information:_
 - MediaWiki version: 1.41
 - Server OS: Debian 11
 - Installed extensions and versions: only the Citizen skin
 - PHP version 8.1

**Comment by ratte1303** [comment]
Solved it by setting:
.citizen-header .citizen-menu-checkbox-checkbox[aria-expanded="true"] ~ .citizen-header__button::before {
	visibility: hidden;
}

Now there is no overlay which makes the close button work at least.

**Comment by alistair3149** [comment]
This will take some time to investigate, I don't have an Apple machine with me at the moment :(

**Comment by alistair3149** [comment]
Should be fixed now. Please feel free to reopen the issue if it still persists
