### ISSUE TITLE
Dark bar on the right on Safari on Mac

### ISSUE THREAD

**Issue by ratte1303** [StarCitizenTools/mediawiki-skins-Citizen#836]
## Describe the Bug
On Safari 17.2.1 on macOS 14.2.1 there always is a dark bar showing on the right of the screen. 
<img width="1350" alt="Bildschirmfoto 2024-05-05 um 09 49 34" src="https://github.com/StarCitizenTools/mediawiki-skins-Citizen/assets/151960006/71abbbf8-d528-428a-a539-01e24fc63b40">

Live demo: todo.wwiki.org

## System
_Please complete the following information:_
 - MediaWiki version: 1.41
 - Server OS: Debian 11
 - Installed extensions and versions: only the Citizen skin
 - PHP version 8.1

**Comment by alistair3149** [comment]
Would you mind to check if the latest commit works?

**Comment by ratte1303** [comment]
Yep, it works.
