### ISSUE TITLE
Buggy Edit Button when using VisualEditor 

### ISSUE THREAD

**Issue by ratte1303** [StarCitizenTools/mediawiki-skins-Citizen#839]
## Describe the Bug
The pen icon displays 2 times and the "edit section" part is weird.
<img width="1476" alt="Bildschirmfoto 2024-05-06 um 17 10 01" src="https://github.com/StarCitizenTools/mediawiki-skins-Citizen/assets/151960006/99c8d85e-ba00-4753-bb46-dad0d6c08961">

live demo: todo.wwiki.org

## Expected Behavior
- Only one pen icon in edit section which takes the user to VisualEditor.
- Only one pen icon on the top for ve-edit

## System
_Please complete the following information:_
 - MediaWiki version: 1.41
 - Server OS: Debian 11
 - Installed extensions and versions: see Special:Version
 - PHP version: 8.1

**Comment by BCMonomial** [comment]
Having the same issue. I mentioned on Issue #812.

**Comment by alistair3149** [comment]
For this issue, does the latest commit fix it?

**Comment by ratte1303** [comment]
Adjusting the loading order and applying the latest commits fixed everything except the Echo buttons :/
Since this is mentioned in #840 I am closing this issue.
