### ISSUE TITLE
Echo icons not displaying correctley 

### ISSUE THREAD

**Issue by ratte1303** [StarCitizenTools/mediawiki-skins-Citizen#840]
## Describe the Bug
When using Echo on first load the corresponding symbols in the header are missing and showing text instead of the icons which makes the header bar take up more space. When clicking either text it reloads and shows the correct icon.

The issue lies in the SkinHooks.php since using the old file from 2.13.1 works.
 
<img width="1476" alt="Bildschirmfoto 2024-05-06 um 17 16 49" src="https://github.com/StarCitizenTools/mediawiki-skins-Citizen/assets/151960006/d11ba13e-46ca-42b0-8710-8aedb7f4e491">

live demo: todo.wwiki.org

## System
_Please complete the following information:_
 - MediaWiki version: 1.41
 - Server OS: Debian 11
 - Installed extensions and versions: see Special:Version
 - PHP version: 8.1

**Comment by ratte1303** [comment]
Adjusting the loading order in the LocalSettings.php didnt fix it for me..
As already mentioned the issue is resolved when using an older verison of the SkinHooks.php.

**Comment by alistair3149** [comment]
Would you be able to give me a test account for the wiki?
Anon can't access the Echo buttons.

**Comment by ratte1303** [comment]
> Would you be able to give me a test account for the wiki? Anon can't access the Echo buttons.

username: test
password: wiki1234

**Comment by alistair3149** [comment]
Would you be able to check if the latest commit fixes it for you?

**Comment by ratte1303** [comment]
Yep, thanks 👍
