### ISSUE TITLE
Buggy Table of Contents on Firefox

### ISSUE THREAD

**Issue by ratte1303** [StarCitizenTools/mediawiki-skins-Citizen#855]
## Describe the Bug
On mobile Firefox using the Table of Contents works but sometimes the small popup is not closing after clicking on a heading.

## Expected Behavior
Table of contents popup always closes after clicking on mobile. 

## System
    MediaWiki version: 1.41
    Server OS: Debian 11
    Installed extensions and versions: only the Citizen skin
    PHP version 8.1

**Comment by alistair3149** [comment]
I will be doing some refactor on the checkbox hacks-related components (including ToC) soon, so this will probably be delayed to after the refactor is done. Please feel free to submit any patches if anyone knows how to fix this :)

**Comment by csalinezh** [comment]
The described issue seems to affect Chrome Android also.

**Comment by alistair3149** [comment]
Is this still reproducible?

**Comment by ratte1303** [comment]
Yes, as you can see on my demo page: arbeit.wiki/Streikrecht

On **Chrome mobile** there are animations and the popup closes when being clicked. 

On **Firefox desktop** there are no animations when a popup such as search is being opened or closed. 

On **Firefox mobile** the table of content popup is animated correctley but only closes when a main heading is clicked. When a sub-heading is clicked the popup still stays open.

I also noticed there is no scrolling animation anymore when clicking links in the table of contents.
