### ISSUE TITLE
Icons for entries of MediaWiki:Sidebar may be missing when used with another skin and $wgEnableSidebarCache

### ISSUE THREAD

**Issue by csalinezh** [StarCitizenTools/mediawiki-skins-Citizen#863]
## Describe the Bug
Citizen adds icons for entries defined in `MediaWiki:Sidebar` by hooking `onSkinBuildSidebar` and modifying `Skin->sidebar`. It tries to avoid interfering with other skins by checking the active skin, as seen in: https://github.com/StarCitizenTools/mediawiki-skins-Citizen/blob/e33098a65ef1de8620e89094dc1a009c98b3d885/includes/Hooks/SkinHooks.php#L103-L104

However, the generated sidebar object may be saved in object cache if `$wgEnableSidebarCache` is true. The cache key used to depend solely on the "user interface language" (`uselang`), see [Skin::buildSidebar@1.39.7](https://github.com/wikimedia/mediawiki/blob/1.39.7/includes/skins/Skin.php#L1515). Therefore if the cached sidebar was generated when serving a Vector user, Citizen users accessing afterwards will not see the icons in sidebar until the cache expires.

It seems to have been fixed in 1.41 by adding skin name in cache key (https://github.com/wikimedia/mediawiki/commit/722cb2e4fea366bf570288958075e0a3cccfa65c). However I think Citizen had better document this incompatibility with `$wgEnableSidebarCache` for users on older versions of mediawiki. It may also make sense to ask them to backport this fix to 1.39 LTS.

1. Install Citizen on mediawiki 1.39. Leave Vector as the default skin.
2. Enable `$wgEnableSidebarCache`.
3. Access any page in Vector. Then add `?useskin=citizen` to switch to Citizen.
4. Open the menu of Citizen and check if the icons are there.

## Expected Behavior
Icons always appear when using Citizen skin.

## System
 - MediaWiki version: v1.39.7

**Comment by alistair3149** [comment]
Thanks for the report! I have started the process of backporting the core change back to 1.39 and hopefully it will make it in soon.
https://gerrit.wikimedia.org/r/c/mediawiki/core/+/1038833

**Comment by alistair3149** [comment]
Closing the issue since the patch is backported into 1.39.
