### ISSUE TITLE
Suggestion: reduce specific margins on UL and OL objects

### ISSUE THREAD

**Issue by TarkusLee** [StarCitizenTools/mediawiki-skins-Citizen#886]
## The Problem
Lists currently have a great deal of margin space surrounding and within them. I would like to suggest reducing the margins in some places.

## In Multi-level lists
Within multi-level lists, there is a large gap between elements. For this I propose a change akin to this:
`.mw-content-ltr li > ul {
	margin-top: 0;
	margin-bottom: 0;
}`

## Following Paragraph Elements
The spacing between paragraphs and lists feels large due to the combined margins of the paragraph element itself and the margin of the list.
For this, I suggest the following:
`p + ol,
p + ul {
	margin: 0 0 var(--space-md) var(--space-lg);
}`

**Comment by alistair3149** [comment]
Do you have a live example of the paragraph element? The margin should combine and I can't reproduce it locally.

**Comment by TarkusLee** [comment]
Sorry, you're correct there. I didn't notice that the two margins do combine together. In that case, I would like to amend my suggestion there:
The spacing between paragraphs and lists feels larger than necessary. I suggest reducing or removing the top margin from lists in order to tighten the association between a paragraph and following list.

A demo of my margin suggestions can be found at [this url](https://www.dustloop.com/w/User:TarkusLee/BrokenLordsStrategy). The CSS can be found [here](https://www.dustloop.com/w/User:TarkusLee/shared/styles.css).

**Comment by alistair3149** [comment]
When the top margin is removed, then the margin will be unbalanced and the list will be visually closer to the elements above the list. How should we handle the situation where the elements below are related to the list? Apart from paragraphs, what other elements should also be adjusted?

**Comment by TarkusLee** [comment]
That I am unsure of. My concern was that lists feel too far detatched from paragraphs that they supplement.
