### ISSUE TITLE
Cargo Tables are slightly too large for the content body of the page

### ISSUE THREAD

**Issue by TarkusLee** [StarCitizenTools/mediawiki-skins-Citizen#888]
Cargo Tables are slightly too large for the content body of the page. This results in a horizontal scroll bar, and the right border of the cargo table being cut off
![image](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/assets/11951612/e7c55aca-83d8-4930-ae25-c276115b7522)

Page demonstrating behavior: [here](https://www.cleanhit.wiki/ST1/Accessories)

**Comment by alistair3149** [comment]
There is something weird going on.
The `citizen-table-wrapper` element should have been removed quite a few patches ago, so it should not be in your current version of Citizen. You might want to do a clean re-install of Citizen to see if it persists, it could be caching issue.

**Comment by TarkusLee** [comment]
The issue has persisted. Here are the steps I took per your last message:

- completely delete the Citizen skin directory
- Visit the page—receive an error describing how the skin is not found
- Download the latest commit of the master branch of this repo
- extract to the Skins directory and name the extracted directory Citizen
- manually purge both the page cache, caches using the maintenance script, and the local browser cache
- wait 2 days for cache information to propagate
- No change

**Comment by alistair3149** [comment]
Ah I found the cause, [MediaWiki:Citizen.js](https://www.cleanhit.wiki/MediaWiki:Citizen.js) is adding the wrapper. Would you mind to remove it and give it another try?

**Comment by TarkusLee** [comment]
Removed the corresponding code snippet, purged cache, pushed an empty edit, and the issue persists.
