### ISSUE TITLE
Close button for search popup not working as expected

### ISSUE THREAD

**Issue by ratte1303** [StarCitizenTools/mediawiki-skins-Citizen#895]
## Describe the Bug
Clicking the close button after opening the search popup results in the search popup opening again with animation instead of closing. 
This is especially important since on Safari mobile you can only close it via the close button because touching the rest of the content doesnt do anything and you would be stuck with the serach popup open. 

## Expected Behavior
Table of contents popup closes after clicking close. 

## System
    MediaWiki version: 1.42
    Server OS: Debian 11
    Installed extensions and versions: only the Citizen skin
    PHP version 8.1
    Live demo: arbeit.wiki

**Comment by alistair3149** [comment]
The closing button issue should be resolved with 317296e. As for the Safari bug, it is still an issue with the commit?
