### ISSUE TITLE
Misleading edit section icons

### ISSUE THREAD

**Issue by ratte1303** [StarCitizenTools/mediawiki-skins-Citizen#897]
## Describe the Bug
Misleading edit section icons for source and visual edit since they are the same.
<img width="320" alt="Screenshot 2024-07-04 110559" src="https://github.com/StarCitizenTools/mediawiki-skins-Citizen/assets/151960006/c8e5f6e3-f350-40fb-bf75-11db81e9aaf1">

## Expected Behavior
Different icons for visual and source edit.

## System
    MediaWiki version: 1.42
    Server OS: Debian 11
    Installed extensions and versions: only the Citizen skin
    PHP version 8.1
    Live demo: arbeit.wiki

**Comment by alistair3149** [comment]
It is a [MediaWiki core bug](https://phabricator.wikimedia.org/T287622) where skin hooks do not execute after extension hooks. In this particular case, the editsection buttons are added by VisualEditor after Citizen process the editsection buttons. The only workaround is to load the Citizen skin after extensions, that is why it is stated in the installation steps too.
