### ISSUE TITLE
"Filter Versions" drop-down menu's background does not fill properly on History pages

### ISSUE THREAD

**Issue by TarkusLee** [StarCitizenTools/mediawiki-skins-Citizen#900]
![image](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/assets/11951612/bb795dda-e0b5-4e15-9122-3bc9bf803c9f)
see the attached screenshot for a better view of the problem.

Can be seen by visiting the history page for a given topic page. Example: https://www.dustloop.com/wiki/index.php?title=GGACR/Venom&action=history

**Comment by alistair3149** [comment]
The background isn't applied through Citizen skin, it is applied locally through [MediaWiki:Ciitzen.css](https://www.dustloop.com/w/MediaWiki%3ACitizen.css#:~:text=Section%20button%20styling%20*********************/-,.mw%2Dcollapsible%2Dtoggle,-%7B%0A%09padding%3A%200.2rem%200.5rem). 

I have checked the other skins and it seems that the button isn't filling the container either. You might want to file it upstream to MediaWiki core.
<img width="1093" alt="image" src="https://github.com/StarCitizenTools/mediawiki-skins-Citizen/assets/9260542/45433b66-5397-41fa-a5e3-76ca12f5e5d6">
