### ISSUE TITLE
#898 introduced new problem

### ISSUE THREAD

**Issue by ciphersimian** [StarCitizenTools/mediawiki-skins-Citizen#903]
## Describe the Bug
Unfortunately while the original issue reported in #898 was fixed, now when you try and `Edit or create page` from the search, the `?action=edit` becomes part of the page name.

1. Toggle the search pop-up with `/`
2. Enter any page name
3. Click the `Edit or create page` button
4. It will take you to the page you entered with `?action=edit` appended as a literal part of the page name.

## Expected Behavior
I expect it to take me to the page entered in the search box, but URL encoded, without anything else appended to it.

## System
 - Citizen version `v2.22.1`
 - MediaWiki version `v1.42.1`
 - Server OS: `Unknown`
 - Installed extensions and versions
   - [DynamicPageList3](https://www.mediawiki.org/wiki/Extension:DynamicPageList3) `v3.5.2`
   - [ParserFunctions](https://www.mediawiki.org/wiki/Extension:ParserFunctions) `v1.6.1`
   - [Scribunto](https://www.mediawiki.org/wiki/Extension:Scribunto)
   - [TemplateStyles](https://www.mediawiki.org/wiki/Extension:TemplateStyles) `v1.0 (7bc4f37) 00:36, 4 July 2024`
   - [Disambiguator](https://www.mediawiki.org/wiki/Extension:Disambiguator) `v1.4 (00030e8) 00:43, 27 June 2024`
   - [IPBLoginAuth](https://www.mediawiki.org/wiki/Extension:IPBAuthLogin) `v1.0.1`
 - PHP version `8.3.8 (cgi-fcgi)`

**Comment by alistair3149** [comment]
Do you have an example of the full URL that you're getting?
