### ISSUE TITLE
mw-headline ending up black in darkmode on Template namespace pages?

### ISSUE THREAD

**Issue by ciphersimian** [StarCitizenTools/mediawiki-skins-Citizen#904]
## Describe the Bug
I can't figure out where this is coming from, but all the headings on my Template pages are black in dark mode:
![image](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/assets/38382607/1073fc0f-2644-49fd-9aa4-592bc402f5dd)

I'm using a stylesheet workaround to fix darkmode issues that has some questionable entries since MediaWiki doesn't support the `prefers-color-scheme: dark` media query, but I can't see any reason why this would only adversely affect pages in the Template namespace and I can't trace any of the styles back to this, but just in the interest of full disclosure this is what I'm currently using via templatestyles (though I don't even think this is getting included in the pages in question, I'm applying this very sparingly only to specific tables/pages with a lot of issues that will be time consuming to fix properly):
```
@media screen {
    html.skin-theme-clientpref-night [style*="background"],
    html.skin-theme-clientpref-night [bgcolor],
/* } */
/* for some reason this isn't working and gives 'Invalid media query' so for now just set it all the time */
/* @media screen and (prefers-color-scheme: dark) { */
    html.skin-theme-clientpref-os [style*="background"],
    html.skin-theme-clientpref-os [bgcolor] {
        color: #000;
    }
/* } */
/* @media screen { */
    html.skin-theme-clientpref-night [style*="background"] a,
    html.skin-theme-clientpref-night [bgcolor] a,
/* } */
/* for some reason this isn't working and gives 'Invalid media query' so for now just set it all the time */
/* @media screen and (prefers-color-scheme: dark) { */
    html.skin-theme-clientpref-os [style*="background"] a,
    html.skin-theme-clientpref-os [bgcolor] a {
        color: #171717;
        text-decoration: underline;
    }
}
```

1. Create a page in the Template namespace with a Heading
Template:Test
```
== Test ==
```
2. Save the page and view it in dark mode
3. The heading is black on a black background
4. When transcluded into another page, the heading shows up fine

## Expected Behavior
The heading with style mw-headline should be visible on pages in all namespaces.

## System
 - Citizen version `v2.22.1`
 - MediaWiki version `v1.42.1`
 - Server OS: `Unknown`
 - Installed extensions and versions
   - [DynamicPageList3](https://www.mediawiki.org/wiki/Extension:DynamicPageList3) `v3.5.2`
   - [ParserFunctions](https://www.mediawiki.org/wiki/Extension:ParserFunctions) `v1.6.1`
   - [Scribunto](https://www.mediawiki.org/wiki/Extension:Scribunto)
   - [TemplateStyles](https://www.mediawiki.org/wiki/Extension:TemplateStyles) `v1.0 (7bc4f37) 00:36, 4 July 2024`
   - [Disambiguator](https://www.mediawiki.org/wiki/Extension:Disambiguator) `v1.4 (00030e8) 00:43, 27 June 2024`
   - [IPBLoginAuth](https://www.mediawiki.org/wiki/Extension:IPBAuthLogin) `v1.0.1`
 - PHP version `8.3.8 (cgi-fcgi)`

**Comment by alistair3149** [comment]
Citizen doesn't set any styles like that, it is from FlaggedRev.
https://codesearch.wmcloud.org/search/?q=html.skin-theme-clientpref-os+%5Bstyle*%3D%22background%22%5D&files=&excludeFiles=&repos=

For some reason, the extensions are not respecting the LESS/skin variables set by Citizen. It is something that I'm investigating currently.

**Comment by alistair3149** [comment]
The FlaggedRev issue is something else that is upstream, so there isn't a need to track it here. Thanks for investigating into the issue!
