### ISSUE TITLE
Skin no longer respects css rule to image zoon on image hover

### ISSUE THREAD

**Issue by TarkusLee** [StarCitizenTools/mediawiki-skins-Citizen#913]
## Describe the Bug
Previously, had this rule added to our citizen.css in order to disable the undesireable zoom effect when hovering over an image.
`.citizen-body a.image:hover:not(.lazy):not(.new) > img {
  transform: none
}`
But after updating, this rule no longer works, and the zoom effect has returned.

Link to an affected page: https://www.dustloop.com/w/GGACR/Venom

To demonstrate the issue, hover over one of the images within cards describing moves within the middle body of the page.

**Comment by alistair3149** [comment]
MediaWiki renders HTML for images differently since MW 1.42. You'll need to update the selector to match it. 

```css
figure[ typeof~='mw:File' ] > a:first-child img,
figure[ typeof~='mw:File/Frameless' ] > a:first-child img,
figure[ typeof~='mw:File/Thumb' ] > a:first-child img,
figure[ typeof~='mw:File/Frame' ] > a:first-child img {
  ...
}
```
