### ISSUE TITLE
Cargo Tables are not styled in the same way as Wikitables or cargo Data Tables

### ISSUE THREAD

**Issue by TarkusLee** [StarCitizenTools/mediawiki-skins-Citizen#923]
After the recent update to wikitable styling, it seems that Cargo tables created with the display=table format have fallen out of parity.
They do not have the border or border-radius of wikitables or dynamic tables.

![image](https://github.com/user-attachments/assets/d5242bc3-f84f-4ba6-8f1d-3ccdab83253b)

An example can be seen with the table here: https://www.dustloop.com/w/GGACR/Mechanics#Wakeup_Animations

**Comment by alistair3149** [comment]
I am unable to reproduce it on the page. Is there additional steps needed to reproduce the bug?

**Comment by TarkusLee** [comment]
I ended up adding custom CSS to my site's citizen.css file in order to achieve visual parity until a potential skin update comes. Because of that, the issue is not visible on my site anymore.

**Comment by TarkusLee** [comment]
The following is the CSS I added to achieve parity:

`/******************* Port Wikitable Styling to Cargo Tables *******************/
.cargoTable {
	border-collapse: collapse;
	border-color: var( --border-color-base );
	border-radius: var( --border-radius-medium );
	box-shadow: var( --box-shadow-border );
}
 .cargoTable caption {
   padding: var(--space-xs) var(--space-sm);
   font-size: var(--font-size-medium);
   font-weight: var(--font-weight-semibold);
   color: var(--color-emphasized);
   text-align: start;
}
.cargoTable th {
  text-align: start;
}
.cargoTable th, .cargoTable td {
  padding: var(--space-xs) var(--space-sm);
}
/* spooky border rules */
.cargoTable tr:first-of-type th:first-child, .cargoTable tr:first-of-type td:first-child {
  border-left-width: 0;
  border-top-left-radius: var(--border-radius-medium);
}
.cargoTable tr:first-of-type th:last-child, .cargoTable tr:first-of-type td:last-child {
  border-right-width: 0;
  border-top-right-radius: var(--border-radius-medium);
}
.cargoTable tr:last-of-type th:first-child, .cargoTable tr:last-of-type td:first-child {
  border-left-width: 0;
  border-bottom-left-radius: var(--border-radius-medium);
}
.cargoTable tr:last-of-type th:last-child, .cargoTable tr:last-of-type td:last-child {
  border-right-width: 0;
  border-bottom-right-radius: var(--border-radius-medium);
}
.cargoTable > :not( [ hidden ] ) ~ :not( [ hidden ] ), .cargoTable > * > :not( [ hidden ] ) ~ :not( [ hidden ] ) {
  border-top: var(--border-width-base) solid var(--border-color-base);
}
.cargoTable > :has( + :not( :empty ) ) tr:last-of-type th:first-child, .cargoTable > :has( + :not( :empty ) ) tr:last-of-type td:first-child {
  border-bottom-left-radius: var(--border-radius-sharp);
}
.cargoTable > :has( + :not( :empty ) ) tr:last-of-type th:last-child, .cargoTable > :has( + :not( :empty ) ) tr:last-of-type td:last-child {
  border-bottom-right-radius: var(--border-radius-sharp);
}
.cargoTable > * + :not( :empty ) tr:first-of-type th:first-child, .cargoTable > * + :not( :empty ) tr:first-of-type td:first-child {
  border-top-left-radius: var(--border-radius-sharp);
}
.cargoTable > * + :not( :empty ) tr:first-of-type th:last-child, .cargoTable > * + :not( :empty ) tr:first-of-type td:last-child {
  border-top-right-radius: var(--border-radius-sharp);
}
.cargoTable--border tr > :not( [ hidden ] ) ~ :not( [ hidden ] ) {
  border-right: var(--border-width-base) solid var(--border-color-base);
  border-left: var(--border-width-base) solid var(--border-color-base);
}

/* in-house stripe settings */
.cargoTable {
	background-color: var(--color-surface-2) !important;
}
.cargoTable tbody tr:nth-child(odd) {
    background-color: var(--color-surface-1) !important;
}
.cargoTable tbody tr:hover {
    background-color: var(--color-surface-2--hover) !important;
}`
