### ISSUE TITLE
Checkboxes appearing inverted

### ISSUE THREAD

**Issue by kirb** [StarCitizenTools/mediawiki-skins-Citizen#931]
## Describe the Bug
Since 2.26.0, checkboxes are appearing inverted. Black hover state and checkmarks appear as white, and vice versa. It also means the unselected state is missing a border, so an unchecked checkbox is invisible.

![image](https://github.com/user-attachments/assets/4d72c419-9cbc-44c0-9ccd-98eb2187aa04)

![image](https://github.com/user-attachments/assets/4c130f90-bf6d-405a-8caa-9f6224f7fdf8)

![image](https://github.com/user-attachments/assets/0369803d-a75c-476e-b0d0-209a6c30cb00)

We currently work around it with:

```css
.oo-ui-iconElement-icon.oo-ui-checkboxInputWidget-checkIcon {
	filter: none;
}
```

Seems to be due to [this commit](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/commit/b922b035ccf9a7bea58f971ae69d55fbd2435967)

## Steps to reproduce the behavior:
1. Set up a wiki with Citizen
2. Go to a page with a checkbox, such as the source editor
3. Hover and toggle checkboxes

## Expected Behavior
Checkboxes should appear with non-inverted colors.

## System
See https://theapplewiki.com/wiki/Special:Version

 - MediaWiki version: 1.41.1
 - Server OS: Ubuntu 24.04
 - Installed extensions and versions: See above
 - PHP version: 8.1.29 (fpm-fcgi)

**Comment by alistair3149** [comment]
Forgot to tag it in the commit but should be fixed by 8de13a1f85e6a292a5c812ed09196abf070c9456
