### ISSUE TITLE
Edit section icons duplicity

### ISSUE THREAD

**Issue by marekspacirek** [StarCitizenTools/mediawiki-skins-Citizen#938]
Hello,

Just a minor bug (that's driving my OCD crazy).

Freshly installed version of MW 1.42.1 with Citizen skin (2.27.0) has problem with duplicate section edit icons for VE and code edit.

Screenshot from MW:
<img width="124" alt="Edit-section-icons" src="https://github.com/user-attachments/assets/4c2bb5bc-de28-426e-8596-40ef439322d8">

Instead of `mw-ui-icon-wikimedia-wikiText` there is `mw-ui-icon-wikimedia-edit`

After editing css directly on the page, here is the required result according to Citizen skin screenshots:
(Only first edit section modified, rest is in the default)
<img width="110" alt="Edit-section-icons-correct" src="https://github.com/user-attachments/assets/cf90305e-def4-4af9-8095-c24cf6bd706f">

Server:
Apache 2.4
PHP 8.2

Skin:
Citizen 2.27.0

Extensions:
Default in MW 1.42.1 (nothing more added)

Thank you

**Comment by marekspacirek** [comment]
Note: Language of MW - CZ (Czech)

Switching back to Citizen version 15.1 (latest version with this style):
<img width="131" alt="Edit-section-icons-15" src="https://github.com/user-attachments/assets/77a4fd94-d3e8-4878-bd42-d37acebc2dd7">

My problem is with differentiation from VE and code edit

**Comment by alistair3149** [comment]
Is the skin loaded after VE?

**Comment by marekspacirek** [comment]
@alistair3149 resolved, thank you very much 😀 Ok didn't expect that. At least I learn that position of loading extensions and skins matter more
