### ISSUE TITLE
In MW 1.43 when the ToC is present the width of the page in Citizen is broken

### ISSUE THREAD

**Issue by DarkGames26** [StarCitizenTools/mediawiki-skins-Citizen#957]
## ToC is present the width of the page in Citizen is broken
I use Citizen for my wiki farm, we are currently testing to migrate to MW 1.43, however I encountered the problem that only when the Summary is present on the page the page seems to exceed the limits and even cross over other elements. Also the width preferences clearly don't work either. 

1. Enter any page that has a table of contents
2. With this done, you can see the issue (example).
3. See error

URL for test: https://central.staging.polandball.wiki/wiki/Minji

![Bug Citizen Extended Width](https://github.com/user-attachments/assets/a242de4a-ff63-460d-b7d4-674a8c377274)
Something like this will be seen when entering the URL as I have styles that modify the appearance, (as I also use a fork of the Citizen) but if you remove the sitewide and globalcss CSS the problem persists:
![2024-10-05_11-06 Citizen Bug](https://github.com/user-attachments/assets/ee302fa4-81d8-4532-be50-5f468681352c)

## Expected Behavior
The expected behavior would normally be that the width of the page does not overrun the limits of other elements and also that the width preferences are read correctly.

## System
_Please complete the following information:_
 - MediaWiki version 1.43.0-alpha
 - Server OS: Ubuntu 22.04.4 LTS
 - Installed extensions:
 - Admin Links
- CheckUser
- CiteThisPage
- Echo
- EditAccount
- Editcount
- GlobalUserrights
- Interwiki
- Linter
- Nuke
- Replace Text
- Translate
- CodeEditor
- CodeMirror 6.0.0
- VisualEditor
- WikiEditor
- Parser hooks
- CategoryTree
- Cite
- CommentStreams
- DummyFandoomMainpageTags
- EmbedVideo
- FloatingUI
- ImageMap
- InputBox
- Math
- MsUpload
- OpenGraphMeta
- ParserFunctions
- Poem
- Portable Infobox Neue
- Scribunto
- SyntaxHighlight
- TabberNeue
- TemplateData
- WikiSEO
- PDF Handler
- VipsScaler
- ConfirmEdit
- hCaptcha
- SpamBlacklist
- TitleBlacklist
- PageImages
- AWS
- Discussion tools
- Global CSS/JS
- GlobalMessages
- Highly Automated Welcome Tool
- Less
- MobileFrontend
- MultimediaViewer
- Plausible
- Previews
- RobotsTxt
- SecureLinkFixer
- SimpleBlogPage
- SiteNotice2
- StaffPowers
- StructuredData
- TemplateWizard
- TextExtracts
- Universal­Language­Selector
This list can be consulted directly: https://central.staging.polandball.wiki/wiki/Special:Version
 - PHP version 8.3.12 (fpm-fcgi)

**Comment by alistair3149** [comment]
It is caused by a local style override. You need to modify the `--header-size` CSS variable when you edit the header styles.
![image](https://github.com/user-attachments/assets/1e7da777-ca51-45f2-be01-ed077e3c0de1)
```css
@media screen and (min-width: 1120px) {
    .citizen-page-container {
        margin-left: var(--header-size);
    }
}
```

**Comment by alistair3149** [comment]
Upon investigation, it seems that the LESS parser is different on MW 1.43, making `--padding-page` to not calculate correctly. The last commit should fix it.

**Comment by DarkGames26** [comment]
That would explain the bug, I didn't read in the release notes in MW 1.43 about the changes in the LESS parser
