### ISSUE TITLE
When using TinyMCE, skin causes infinite scroll

### ISSUE THREAD

**Issue by sunnywinterday** [StarCitizenTools/mediawiki-skins-Citizen#978]
## Same as title, when you try to edit with TinyMCE, Citizen causes the page to become infinitely longer over time. 

1. Attempt to edit with TinyMCE while Citizen is the selected skin

## Expected Behavior
No infinite scroll, able to edit and save.

## System
_Please complete the following information:_
 - MediaWiki version 1.42.3
 - Server OS: Ubuntu-Latest
 - Installed extensions and versions TinyMCE 1.1.2, Bootstrap 5.0.0
 - PHP version 8.3

**Comment by sunnywinterday** [comment]
So I've found out that it's an issue with TinyMCE's auto resize, and removing the functionality by renaming the folder makes the issue disappear.

How can we solve this without a workaround?

**Comment by sunnywinterday** [comment]
@alistair3149 I can walk you through it to show you. Is here the best way to communicate?

**Comment by alistair3149** [comment]
> @alistair3149 I can walk you through it to show you. Is here the best way to communicate?

Yes :) Here would be the best place since it can be kept for references.

**Comment by sunnywinterday** [comment]
Hmm. The site I observed the issue on is private. 

I read a lot about it, it seems that all it would take is a site, with this skin (it happens to some others too), with the TinyMCE extension added. Press the [Edit} button (not edit source) to use the TinyMCE UI and it will cause the page to become infinitely larger. If you would like a demo we can get together, but that's all it is.

**Comment by alistair3149** [comment]
Hi sorry for getting to you back late, it took me a while to find the real culprit.
Apparently TinyMCE autoresize does not play nice with having a `min-height` in the `<html>` element. I have moved the rule to only the `<body>` element instead and it fixed the issue.

**Comment by sunnywinterday** [comment]
Thank you for taking the time to look into this! I would like to test this out, time permitting. I will come back, God willing, with results when and if I do!

**Comment by sunnywinterday** [comment]
It was not resolved with the changes. I did notice in the commit you mentioned that setting a max height fixed it. Is there a reason the code in ext.tinymce.less sets the min height?

`
body.mce-content-body {
	min-height: auto;
}
`
